### ISSUE TITLE
AoC files operations not working for workspace-less users

### ISSUE THREAD

**Issue by raziel-j** [IBM/aspera-cli#109]
So this is awesome and got it working for me.
however i cannot get it working for an external partner that has folder shares given by us but is not a workspace member. they do not need to see everything we are working on. they do not have a default workspace. ibm support said log my problem

mine =
ascli aoc files browse /
Current Workspace: <redacted>
Items: 2/2
+---------------+------+----------------+------+----------------------+--------------+
| name          | type | recursive_size | size | modified_time        | access_level |
+---------------+------+----------------+------+----------------------+--------------+

not mine =
ascli aoc files browse /
ERROR: Other: No such workspaces: <redacted>
ERROR: Argument: unprocessed values: ["/"]

ascli aoc files browse /
Current Workspace: undefined
ERROR: Other: Cannot get user's home node id, check your default workspace or specify one
ERROR: Argument: unprocessed values: ["/"]

is you want debug output let me know but i feel its a miss config from me

**Comment by laurent-martin** [comment]
If I understand well, you are not part of any workspace, but a folder is shared with you in that organization ?

**Comment by raziel-j** [comment]
not me but another person, BUT yes that is the issue

**Comment by laurent-martin** [comment]
Can you , or your user , try this version of the gem, that's the development branch current version:
https://ibm.biz/aspera-cli-beta

If the user uses the docker version, let me know.

**Comment by raziel-j** [comment]
Have done testing and can confirm it work

---
config:
  version: 4.13.0.pre
---

ascli aoc files browse /
Current Workspace: undefined
Items: 2/2
+------------------------+------+----------------+------+----------------------+--------------+
| name                      | type | recursive_size | size | modified_time                | access_level |
+------------------------+------+----------------+------+----------------------+--------------+
| This_Is_A_Test         | link  |                       |        | 2023-03-31T12:15:46Z |                   |
| This_Is_A_Test_Too  | link  |                       |        | 2023-04-03T11:39:04Z |                   |
+------------------------+------+----------------+------+----------------------+--------------+

**Comment by laurent-martin** [comment]
Good news, thanks for the contribution !

**Comment by laurent-martin** [comment]
in next version 4.13
