### ISSUE TITLE
Aspera CLI Directory ownership issue

### ISSUE THREAD

**Issue by mukeshrsharma** [IBM/aspera-cli#111]
Hi Team
After Transfer data from Aspera CLI tool the ownerahip of Directory  are getting changed, So whatever Ownership is there on the Source directory we want to keep the same ownership at destination, we are using below command to tranfer data, please assist
/usr/local/.aspera/cli/bin/aspera shares download -i -H=[sgscvau50097.in623.corpintra.net](https://sgscvau50097.in623.corpintra.net/) --username AGSC_RDI_s_transfe -s=/source_path -d=/Destination_path

**Comment by laurent-martin** [comment]
Hi,

The command line `aspera` (version 3) is deprecated.

This github is about version 4 only.

So, first user version 4. (the version of this github)

Concerning "Shares", it is usually not supposed to keep the ownership of original files.
