### ISSUE TITLE
aoc: Renaming link for shared folder

### ISSUE THREAD

**Issue by knapsu** [IBM/aspera-cli#115]
Aspera CLI version: `3.x`, `4.x`

Problem:
I am unable to rename links to shared folders that are created by Aspera in root folder when someone shares a folder with me (adds as a collaborator).

There is a command `ascli aoc files rename ...` but it forks only with 'file' and 'folder' objects, not 'link' objects.

**Comment by laurent-martin** [comment]
Please check with version 4.14 , this should be fixed
