### ISSUE TITLE
Faspex5 not reading default preset v4.13

### ISSUE THREAD

**Issue by ggaffield** [IBM/aspera-cli#119]
I'll give you the issues I'm having up front and follow with context (aka my story):
1) The faspex5 plugin does not read/find the **default** preset as saved by the wizard.
2) The faxpex5 wizard does not prompt for **username**.
---
Here's the scenario...

After running `ascli config wizard --value=faspex5` and being prompted for url, private key file, client ID and client secret, I get the following:
```
Setting config preset as default for faspex5
Saving config file.
Done.
You can test with:
ascli faspex5 user profile show
```
When try `ascli faspex5 user profile show` or `ascli faspex5 packages list`, I receive the following error:
```
ERROR: Argument: Missing mandatory option: url
Use option -h to get help.
```

The `ascli config preset overview` command shows me the presets, and indeed, there is a default defined and pointing to the wizard created entry.
```
+--------------------------------+---------------+----------------------------------------------+
| config                         | parameter     | value                                        |
+--------------------------------+---------------+----------------------------------------------+
| config                         | version       | 4.13.0                                       |
| default                        | faspex5       | faspex5_bhtransfer02lp_sax_org               |
| faspex5_bhtransfer02lp_sax_org | url           | https://bhtransfer02lp.sax.org/aspera/faspex |
| faspex5_bhtransfer02lp_sax_org | auth          | jwt                                          |
| faspex5_bhtransfer02lp_sax_org | private_key   | 🔑                                           |
| faspex5_bhtransfer02lp_sax_org | client_id     | c227d56b-e9bc-414d-8777-3dc410506bd5         |
| faspex5_bhtransfer02lp_sax_org | client_secret | 🔑                                           |
+--------------------------------+---------------+----------------------------------------------+
```

If I specify the preset by adding `--preset=faspex5_bhtransfer02lp_sax_org` to the command line, I get the following error:
```
ERROR: Argument: Missing mandatory option: username
Use option -h to get help.
```

And finally, when I add `--username=glenn.gaffield@sax.org`, it works! : 
```
+------------------------------+-----------------------------------------------------------------------------------------------------+
| key                          | value                                                                                               |
+------------------------------+-----------------------------------------------------------------------------------------------------+
| can_have_public_url          | default                                                                                             |
| public_url_enabled           | false                                                                                               |
| can_create_from_remote       | false                                                                                               |
| can_disable_connect          | false                                                                                               |
| connect_disabled             | false                                                                                               |
| can_edit_email               | false                                                                                               |
| email                        | Glenn.Gaffield@sax.org                                                                              |
| show_only_completed_packages | false                                                                                               |
| rows_per_page                | 10                                                                                                  |
| can_change_password          | false                                                                                               |
| locale                       | none                                                                                                |
| client_settings              | {"changeDownloadLocationDismissed":false,"skipWelcomeScreen2021":true,"hideMobileDownloadAd":false} |
| public_key                   | 🔑                                                                                                  |
+------------------------------+-----------------------------------------------------------------------------------------------------+
```

**Comment by laurent-martin** [comment]
As there is no answer, I will those this ticket.
If there is still the issue after next release, you may re-open it.

**Comment by ggaffield** [comment]
Sorry, I got busy. My initial try resulted in an error. I then needed time to retest and document in order to give you useful feedback. But I haven’t had the time yet. -Glenn ----------------------------------(sent from my cell phone)On Sep 12, 2023, at 4:55 AM, Laurent Martin ***@***.***> wrote:﻿
As there is no answer, I will those this ticket.
If there is still the issue after next release, you may re-open it.

**Comment by ggaffield** [comment]
My attempt to use the faspex5 wizard on 4.14 beta:

ascli config wizard --value=faspex5 --log-level=debug

[snip]

option: url> http://transfer.xyz.org
D, [2023-09-13T15:21:20.180417 #21659] DEBUG -- : (value/interactive) set url=http://transfer.xyz.org
D, [2023-09-13T15:21:20.180724 #21659] DEBUG -- : (value) get id=
D, [2023-09-13T15:21:20.180927 #21659] DEBUG -- : (value) get value=faspex5
ERROR: Other: uninitialized constant Aspera::Cli::Plugins::Faspex5
/usr/local/bundle/gems/aspera-cli-4.14.0.pre/lib/aspera/cli/plugins/config.rb:318:in `plugin_class': uninitialized constant Aspera::Cli::Plugins::Faspex5 (NameError)

            return Object.const_get("#{module_full_name}::#{plugin_name_sym.to_s.capitalize}")
                         ^^^^^^^^^^
Did you mean?  Aspera::Fasp
        from /usr/local/bundle/gems/aspera-cli-4.14.0.pre/lib/aspera/cli/plugins/config.rb:942:in `execute_action'
        from /usr/local/bundle/gems/aspera-cli-4.14.0.pre/lib/aspera/cli/main.rb:334:in `process_command_line'
        from /usr/local/bundle/gems/aspera-cli-4.14.0.pre/bin/ascli:29:in `<top (required)>'
        from /usr/local/bundle/bin/ascli:25:in `load'
        from /usr/local/bundle/bin/ascli:25:in `<main>'

**Comment by laurent-martin** [comment]
Thanks for testing, yes, I tested only without --value , i.e. guessing the app by URL only, that should be fixed in version I posted here:
https://ibm.biz/aspera-cli-beta

Note:
It's better, for Faspex5 to provide the URL like: https://transfer.xyz.org/aspera/faspex

like:
```bash
ascli config wizard --url=https://transfer.xyz.org/aspera/faspex
```

Or you can just not give any option.

But that should also work now:

```bash
ascli config wizard --value=faspex5
```

Or:

```bash
ascli config wizard --value=faspex5 --url=https://transfer.xyz.org/aspera/faspex
```

**Comment by ggaffield** [comment]
I tried docker://martinlaurent/ascli:4.14.0
Progress!

I can create a faspex5 preset using the `ascli config wizard --value=faspex5` command and `ascli faspex5 ...` commands use it.  However, they all fail with the following error:

```
Singularity> ascli faspex5 user profile show
ERROR: Rest: Check that your JWT payload matches the required specification. Error: - Invalid subject
status: Bad Request
code: 2019
trace: 072fddf8-92fd-4a4e-807c-aeed869767db
transfer.jax.org 400 Bad Request
```

Here are some relevant debug lines:
`D, [2023-09-26T11:44:33.558096 #105752] DEBUG -- : JWT jwt_payload=[{:exp=>1695746673, :nbf=>1695742773, :iat=>1695742774, :jti=>"ca280c2f-ce05-4ef4-b3f5-5ada8a046bfd", :iss=>"[SNIP]", :aud=>"[SNIP]", :sub=>"user:ggaffig"}]`


`D, [2023-09-26T11:44:33.561803 #105752] DEBUG -- : call_data = {:base_url=>"https://transfer.xyz.org/aspera/faspex/auth", :redirect_max=>2, :auth=>{:type=>:none}, :not_auth_codes=>["401"], :operation=>"POST", :subpath=>"token", :headers=>{"Accept"=>"application/json", "User-Agent"=>"ascli"}, :www_body_params=>{:client_id=>"[SNIP]", :grant_type=>"urn:ietf:params:oauth:grant-type:jwt-bearer", :assertion=>"[SNIP]"}}`

**Comment by laurent-martin** [comment]
Check that the email of user is correct, it is case sensitive.

```bash
ascli conf preset over
```

change if needed with:

```bash
ascli conf preset set [preset name] username [good email]
```

**Comment by ggaffield** [comment]
Ah, you're correct.  It's been awhile since I've worked with this, and I forgot username is an email address.
It now works as it should.
Thanks again for addressing the issue.  Great job!
