### ISSUE TITLE
Publish a pre-release Gem to Rubygems.org

### ISSUE THREAD

**Issue by gegles** [IBM/aspera-cli#12]
After speaking with Brian & Erik, we decided to start pushing pre-release Gems for various folks to have early access to this and test it out.

Let's start with `aspera-cli v4.0.0.beta1`.

**Comment by dwosk** [comment]
https://rubygems.org/gems/aspera-cli

Will need to check back in a day or so to make sure the documentation has been populated.

**Comment by laurent-martin** [comment]
you missed renaming bin/acli to bin/ascli

**Comment by gegles** [comment]
> you missed renaming bin/acli to bin/ascli

duh! Thank you! Will fix it ASAP.
