### ISSUE TITLE
Help: Downloading files with aspera-cli

### ISSUE THREAD

**Issue by asdspal** [IBM/aspera-cli#122]
I need to download this [dataset][1] urgently to cloud server for processing. It is more than 250gb. It can be downloaded using aspera-connect with firefox aspera-faspex extension in desktop. I don't have time to download and transfer it to cloud account. I've tried using aspera-cli, couldn't get it to work. Please can someone guide me? Any help is appreciated.

  [1]: https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=83593077

**Comment by laurent-martin** [comment]
do this:

```bash
ascli faspex package recv --link='https://faspex.cancerimagingarchive.net/aspera/faspex/external_deliveries/384?passcode=cb5318b4d9b5b38d2a5055f04f6ffe9aaa9c0c8b'
```

**Comment by asdspal** [comment]
Thank you very much. It worked.
