### ISSUE TITLE
Files upload to shared folder using private link

### ISSUE THREAD

**Issue by neildonnell** [IBM/aspera-cli#129]
Hi,

Nice program, thank you for the considerable work you have done on this.

I have run into a problem trying to upload a file to a AOC folder that is shared with me (link).

I always seem to get the error:  ERROR: Other: do not use both link and url options

This is an example of the command I try and use:

ascli aoc files upload --workspace=ipl-test --to-folder=/ #2871FFD.jpg --link=test

I've tried many forms of formatting, it seems as soon as I use --link to access a share I get the error.

Is this a bug or can you assist?

Thank you.

**Comment by laurent-martin** [comment]
Effectively,

AoC provides a few ways to Authenticate/Authorize (all based on OAuth 2): web, jwt, public_link

- `jwt` is what is typically used, together with a private key, and requires an account.
- `public_link` is an anonymous, and just the link has it all: AoC instance URL and authorization.

Currently (4.14) option `link` accepts only public links, but not private links.

public links bear a an authorization, while private links require authentication.

So, the question is: is the link you use a public or private link ?

If it's a public link, it can work, but you cannot provide both the authentication and public link authorization, hence the error.

Maybe you have a default preset defined.

To tell `ascli` to not load a default preset, add option `-N` (no default).

If it's a private link, well you will have to wait for a future release.

**Comment by neildonnell** [comment]
Hi Laurent,

Thank you for the information.  The links that I use are all private so
this feedback helps explain what I am seeing.

I am really suffering with running an AOC syncing process and it looks like
CLI approach is also not workable.  Perhaps you can help guide me.

I have a server set-up where I would like content that is added to some
specific workspace folders to be auto-uploaded to the identically named
Aspera Workspace Folder.  I have about 30 Workspaces with Project Named
folders shared to me within them.

Workspace-1/Project 1
Workspace-1/Project 2
Workspace-2/Project 1
Workspace-2/Project 2

I have these all enabled in the Windows Sync Client and I am copying
content to them.

I have tried using the Aspera Connect client on Windows to do this but it
seems to have some issues:

   1. It doesn't *seem* to run as a service or when I disconnect from a
   remote desktop connection.
   2. If I am added to a new shared folder (e.g. Project 3).  Connect
   doesn't seem to auto update and start listing this folder within explorer.
   I either need to restart the machine or run a sync reset.  I am not sure
   which as the results are so inconsistent.
   3. Folders that are Shared within Aspera get (Shared) appended to their
   file name in Windows Explorer. This is quite unhelpful and means I have to
   do some folder name wrangling depending on whether I created a project or
   someone else did.

Do you know when the CLI might support private folders?  This really should
have been a simple job and I have spent days trying to get something that
works quickly for folders and shared folders(links).

Any help you can offer would be muchly appreciated.

Thank you.

Neil

**Comment by laurent-martin** [comment]
I will look at adding private link support ..

**Comment by neildonnell** [comment]
Thank you Laurent,  this is far quicker than I expected.   I have tried
this today and it works!

The problem I now face though is how to build/get the link
'programmatically' as I have scripts that work based on agreed folder name
conventions.  Is there any way this could work with the shared folder name
only? or a way to retrieve the url from the shared folder name so I can
populate the url from that?  Note that my admin has shortlinks type set so
I am not sure if the full length urls are of a logical nature.

Thank you once again for your hard work on this.

-Neil

**Comment by laurent-martin** [comment]
If you get the private link, you can retrieve the folder name, it is displayed when doing a `browse`.
Or you can also do:

```bash
ascli aoc files show / --fields=name --url=https://privatelinkhere --display=data
```

Then, if you want your scripts to use only that name, you can create a preset with the link:

```bash
ascli conf preset set myfoldername url https://private_link
```

Then, you can simply use that link with option `-Pmyfolder`

You can also prefix the preset with some fixed prefix, like `priv_`, example:

```bash
privlink=https://privlinkhere
prefix=priv_

foldername=$(ascli aoc files show / --fields=name --url=$privlink --display=data)

ascli conf preset set $prefix$foldername url $privlink
```

Now you can use the folder name without the url:

```bash
ascli aoc files browse / -P$prefix$foldername
```

**Comment by neildonnell** [comment]
Thank you Laurent but this would still require me to do the management of a
lot of links. I would almost need to keep a database of them and build a
profile every time I am added to a new share, which is kind of what I
expect Aspera to be doing as it is exposing these through the Connect tool.

All I want to do is have a network share of folders like this:
WorkspaceName/Foldername continuously sync to Aspera
WorkspaceName/Foldername with exactly the same names.  These folders can be
a combination of self created or shared folders.

I have about 20 Workspaces, each with up to 10 folders in and people will
add me to new shared folders all the time.

My use case seems really quite simple and I can't believe it's not
possible.  It feels like this is what the Connect Sync tool is for but that
seems to fail when accessing Shared folders, it syncs some content and then
just keeps looping around on an individual file for hours on end.  Do you
know if the Connect tool is actually designed to Sync against shared
folders?

The log file just sits there repeating these lines.

2023-11-06 10:26:24.023 [2724-00001d30] LOG [Sync_reporter] SYNC SESSION
PROG id=e971dd9c-2b5f-4aaf-847a-f03650684f03
name=588a16b3a81d04ce9c346fd84a833c9f progress
dir/xfr/dup/exs/skp/del/mov/err/cfl=7223/8414/0/0/0/71/0/0/0 bytes
xfr/dup/exs/skp/del/mov/err/cfl=11149376731/0/0/0/301536155/0/0/0 xfer
push/pull=0/0
2023-11-06 10:26:24.023 [2724-00001d30] LOG [Sync_reporter] SYNC SESSION
STATS id=e971dd9c-2b5f-4aaf-847a-f03650684f03
name=588a16b3a81d04ce9c346fd84a833c9f scan
f/u/f/d/s/l/e=35/0/265006/231089/0/0/0 notifier
fn/fc/fd/fm/dn/dd/dm/sn/sd/sm=10674/0/0/0/8668/0/0/0/0/0 candidates
fa/fr/fd/fa/da/dr/dd/da=10816/10816/10674/142/8669/8669/8668/1 msgssent
mrq/crq/cnc/mrp/crp/crs=143/71/0/15566/8343/8343 msgsrecd
mrq/crq/cnc/mrp/crp/crs=15566/8343/0/143/71/871 transfers s/d/f=8414/8414/0
queues cn/coi/coo/cki/cko/si/ri/ro/i/o=0/0/0/0/0/0/0/0/0/0 progress
t/p/s/e/c/pc=15566/0/15566/0/0/0 bytes
t/p/s/e/c/pc=10847840576/0/10847840576/0/0/0
2023-11-06 10:26:24.428 [2724-00001d30] LOG [Sync_reporter] SYNC SESSION
SCAN START id=05f73645-5565-4921-a3ea-476c0282a32e
name=476ce04a04a6d983e09e96c9c73e1ebd, directory="/"
2023-11-06 10:26:24.438 [2724-00002158] LOG [Sync_algo/0]
Sync_algo::Retrieve_not_visited: Number of potential deleted nodes: 0
2023-11-06 10:26:24.438 [2724-00001d30] LOG [Sync_reporter] SYNC SESSION
SCAN DONE id=05f73645-5565-4921-a3ea-476c0282a32e
name=476ce04a04a6d983e09e96c9c73e1ebd, directory="/"
2023-11-06 10:26:26.024 [2724-00001d30] LOG [Sync_reporter] SYNC SESSION
PROG id=05f73645-5565-4921-a3ea-476c0282a32e
name=476ce04a04a6d983e09e96c9c73e1ebd progress
dir/xfr/dup/exs/skp/del/mov/err/cfl=0/0/0/0/0/0/0/0/0 bytes
xfr/dup/exs/skp/del/mov/err/cfl=0/0/0/0/0/0/0/0 xfer push/pull=0/0
2023-11-06 10:26:26.024 [2724-00001d30] LOG [Sync_reporter] SYNC SESSION
STATS id=05f73645-5565-4921-a3ea-476c0282a32e
name=476ce04a04a6d983e09e96c9c73e1ebd scan f/u/f/d/s/l/e=107/0/321/0/0/0/0
notifier fn/fc/fd/fm/dn/dd/dm/sn/sd/sm=0/0/0/0/0/0/0/0/0/0 candidates
fa/fr/fd/fa/da/dr/dd/da=0/0/0/0/1/1/1/0 msgssent
mrq/crq/cnc/mrp/crp/crs=0/0/0/0/0/0 msgsrecd
mrq/crq/cnc/mrp/crp/crs=0/0/0/0/0/0 transfers s/d/f=0/0/0 queues
cn/coi/coo/cki/cko/si/ri/ro/i/o=0/0/0/0/0/0/0/0/0/0 progress
t/p/s/e/c/pc=4/0/4/0/0/0 bytes t/p/s/e/c/pc=57580267/0/57580267/0/0/0
2023-11-06 10:26:26.024 [2724-00001d30] LOG [Sync_reporter] SYNC SESSION
PROG id=0705528a-18a2-4f27-9aaa-4e5cdd3156cd
name=4bff0e2e3ce72ec319723bad56f947e8 progress
dir/xfr/dup/exs/skp/del/mov/err/cfl=1/0/0/0/0/0/0/0/0 bytes
xfr/dup/exs/skp/del/mov/err/cfl=0/0/0/0/0/0/0/0 xfer push/pull=0/0
2023-11-06 10:26:26.024 [2724-00001d30] LOG [Sync_reporter] SYNC SESSION
STATS id=0705528a-18a2-4f27-9aaa-4e5cdd3156cd
name=4bff0e2e3ce72ec319723bad56f947e8 scan f/u/f/d/s/l/e=106/0/0/0/0/0/0
notifier fn/fc/fd/fm/dn/dd/dm/sn/sd/sm=0/0/0/0/0/0/0/0/0/0 candidates
fa/fr/fd/fa/da/dr/dd/da=0/0/0/0/1/1/0/1 msgssent
mrq/crq/cnc/mrp/crp/crs=1/0/0/1/0/0 msgsrecd
mrq/crq/cnc/mrp/crp/crs=1/0/0/1/0/0 transfers s/d/f=0/0/0 queues
cn/coi/coo/cki/cko/si/ri/ro/i/o=0/0/0/0/0/0/0/0/0/0 progress
t/p/s/e/c/pc=1/0/1/0/0/0 bytes t/p/s/e/c/pc=0/0/0/0/0/0
2023-11-06 10:26:26.024 [2724-00001d30] LOG [Sync_reporter] SYNC SESSION
PROG id=e971dd9c-2b5f-4aaf-847a-f03650684f03
name=588a16b3a81d04ce9c346fd84a833c9f progress
dir/xfr/dup/exs/skp/del/mov/err/cfl=7223/8414/0/0/0/71/0/0/0 bytes
xfr/dup/exs/skp/del/mov/err/cfl=11149376731/0/0/0/301536155/0/0/0 xfer
push/pull=0/0
2023-11-06 10:26:26.024 [2724-00001d30] LOG [Sync_reporter] SYNC SESSION
STATS id=e971dd9c-2b5f-4aaf-847a-f03650684f03
name=588a16b3a81d04ce9c346fd84a833c9f scan
f/u/f/d/s/l/e=35/0/265006/231089/0/0/0 notifier
fn/fc/fd/fm/dn/dd/dm/sn/sd/sm=10674/0/0/0/8668/0/0/0/0/0 candidates
fa/fr/fd/fa/da/dr/dd/da=10816/10816/10674/142/8669/8669/8668/1 msgssent
mrq/crq/cnc/mrp/crp/crs=143/71/0/15566/8343/8343 msgsrecd
mrq/crq/cnc/mrp/crp/crs=15566/8343/0/143/71/871 transfers s/d/f=8414/8414/0
queues cn/coi/coo/cki/cko/si/ri/ro/i/o=0/0/0/0/0/0/0/0/0/0 progress
t/p/s/e/c/pc=15566/0/15566/0/0/0 bytes
t/p/s/e/c/pc=10847840576/0/10847840576/0/0/0

I really do appreciate your help here as I can find no other resources to
help atm.

Thank you,

Neil
