### ISSUE TITLE
Huge file uploads failing through Aspera Ruby CLI With "Insufficient permissions" Error

### ISSUE THREAD

**Issue by LikhitSankala** [IBM/aspera-cli#133]
Hi Team,

User was unable to upload a large file which was of 39GB size through Ruby cli and is getting an error message "Insufficient permissions" (Error 51 [Source: Permission denied]).
However, user was able to upload the same files if we split into smaller size which is of 3GB each. Therefore, the user has the required permissions to upload the files. 
 
Kindly note that, further details of the issue can be found under IBM case 'TS014807826'.
Could you please check on this issue and provide a fix for Aspera Ruby CLI.

Thanks and Regards,
Likhit.

**Comment by laurent-martin** [comment]
See <https://github.com/IBM/aspera-cli/blob/develop/BUGS.md>

If the problem consists in a transfer failing, it might be due to some configuration aspects of IBM products.

For this particular problem:
Does the upload work using Aspera Connect and the web UI, in the same conditions ?
Or is there the same error ?
(if there is the same error, then it's not a problem with ascli).

**Comment by LikhitSankala** [comment]
Hi Laurent,

Greetings of the day.

There is a huge difference between the transfer rates(upload rates) of Web UI and CLI, the user has used the Aspera Ruby CLI since they had to upload the file of 39GB size.
Transfer Rates:
UI -> 4Mbps
CLI -> 650Mbps
Therefore, could you please check the huge file uploads issue from Aspera Ruby CLI, as the transfer rates are faster when the user wants to upload huge files using the CLI.


Best Regards,

***@***.***<https://www.arm.com/>
Likhit Sankala
L2 Support Engineer - IP Delivery
Email: ***@***.******@***.***>
Working Hours: 07:00 - 16:00 GMT

**Comment by laurent-martin** [comment]
CLI and web UI shall be the same speed if connect client is used. User shall not use http transfer. I proposed a oersonnal webex help which was refused. Can't do better.

**Comment by LikhitSankala** [comment]
Hi Laurent,

Greetings of the day.
Wish you a very happy new year!

Thank you for your response.

We understand that using Aspera Connect will increase the speed of uploads/downloads.
The issue here is that, even though the user has appropriate upload rights to the specific shared inbox in Aspera Dropzones, Aspera Ruby CLI reported "Insufficient Permissions" error, while the user was trying to upload a file of 39GB size. However, when the user split the 39GB file into 13 parts (3GB each file size) and re-tried upload to the same shared inbox using Ruby CLI, the 13 files(3GB each) uploads were successful. Therefore, suggesting that user has the appropriate upload permissions to the shared inbox in Aspera Dropzones.

Could you please check and let us know, why the CLI reported "Insufficient Permissions" error, while the user was trying to upload a file of 39GB. But, the 13 files (3GB each) were uploaded successfully, without any issue. Is there any limitation on the file size which can be uploaded via Ruby CLI to Aspera Dropzones. If not, we are interested in understanding, why the 13, 3GB files were uploaded successfully, while the 39GB file upload failed with "Insufficient Permissions" error (the user has upload access to shared inbox, so the reported error "Insufficient Permissions" seems wrong).

Kindly find more details about the issue in the IBM support case TS014807826.

Best Regards,

***@***.***<https://www.arm.com/>
Likhit Sankala
L2 Support Engineer - IP Delivery
Email: ***@***.******@***.***>
Working Hours: 07:00 - 16:00 GMT

**Comment by LikhitSankala** [comment]
Hi Team,

Greetings of the day.
Hope you are well.

Could you kindly provide an update on this huge size file uploads failing with Insufficient Permissions error using Aspera Ruby CLI issue.

Thank you.

Best Regards,

***@***.***<https://www.arm.com/>
Likhit Sankala
L2 Support Engineer - IP Delivery
Email: ***@***.******@***.***>
Working Hours: 07:00 - 16:00 GMT


From: Likhit Sankala
Sent: Wednesday, January 3, 2024 3:07 PM
To: IBM/aspera-cli ***@***.***>; IBM/aspera-cli ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [IBM/aspera-cli] Huge file uploads failing through Aspera Ruby CLI With "Insufficient permissions" Error (Issue #133)

Hi Laurent,

Greetings of the day.
Wish you a very happy new year!

Thank you for your response.

We understand that using Aspera Connect will increase the speed of uploads/downloads.
The issue here is that, even though the user has appropriate upload rights to the specific shared inbox in Aspera Dropzones, Aspera Ruby CLI reported "Insufficient Permissions" error, while the user was trying to upload a file of 39GB size. However, when the user split the 39GB file into 13 parts (3GB each file size) and re-tried upload to the same shared inbox using Ruby CLI, the 13 files(3GB each) uploads were successful. Therefore, suggesting that user has the appropriate upload permissions to the shared inbox in Aspera Dropzones.

Could you please check and let us know, why the CLI reported "Insufficient Permissions" error, while the user was trying to upload a file of 39GB. But, the 13 files (3GB each) were uploaded successfully, without any issue. Is there any limitation on the file size which can be uploaded via Ruby CLI to Aspera Dropzones. If not, we are interested in understanding, why the 13, 3GB files were uploaded successfully, while the 39GB file upload failed with "Insufficient Permissions" error (the user has upload access to shared inbox, so the reported error "Insufficient Permissions" seems wrong).

Kindly find more details about the issue in the IBM support case TS014807826.

Best Regards,

***@***.***<https://www.arm.com/>
Likhit Sankala
L2 Support Engineer - IP Delivery
Email: ***@***.******@***.***>
Working Hours: 07:00 - 16:00 GMT

**Comment by laurent-martin** [comment]
Hi LikhitSankala,

We need to inspect the log information, that's why I proposed an interactive session.
The used can add the following option to the command line:

```
--transfer-info=@json:'{"ascp_args":["-DDL-"]}'
```

see:
https://github.com/IBM/aspera-cli/tree/main?tab=readme-ov-file#direct

and then extract lines that have `ERR:`

**Comment by laurent-martin** [comment]
no news
