### ISSUE TITLE
ascp/fasp download  from ebi gives 'Deprecated peer license' error

### ISSUE THREAD

**Issue by mdehollander** [IBM/aspera-cli#137]
At least at my end the command to download data from ena/ebi no longer works. I used the command specified at https://github.com/IBM/aspera-cli/issues/89#issuecomment-1230421746 in January, and than it worked. Now it returns with an error. Could it be that there something general has changed at EBI? This is what I get:

```
ascli -N server download --url=ssh://fasp.sra.ebi.ac.uk:33001 --username=era-fasp --ts=@json:'{"token":""}' --to-folder=. /vol1/fastq/SRR123/036/SRR12397036/SRR12397036_2.fastq.gz
 Time: 00:00:00 =---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---= 0% 0 Mbps  ETA: ??:??:??
E, [2024-03-13T15:58:12.581419 #3204711] ERROR -- : ascp failed: pid 3204715 exit 1
W, [2024-03-13T15:58:12.581663 #3204711]  WARN -- : An error occurred during transfer: Failure processing peer license: Deprecated peer license
W, [2024-03-13T15:58:12.581807 #3204711]  WARN -- : Resuming in 2 seconds (retry left:6)
E, [2024-03-13T15:58:16.176103 #3204711] ERROR -- : ascp failed: pid 3204720 exit 1
W, [2024-03-13T15:58:16.176317 #3204711]  WARN -- : An error occurred during transfer: Failure processing peer license: Deprecated peer license
E, [2024-03-13T15:58:16.176466 #3204711] ERROR -- : non-retryable error
ERROR: Transfer: Failure processing peer license: Deprecated peer license
```

I also get it when I use ascp directly from the aspera connect client.

**Comment by laurent-martin** [comment]
It might be a problem on server side.
This error, IIRC, means that the license file on the other is not world-readable.

**Comment by mdehollander** [comment]
Ok, thanks for the quick reply and the confirmation. Contacting ENA/EBI support normally has a response time of a few weeks, so that's why I tried here first :)

**Comment by laurent-martin** [comment]
One way to check the problem is the following: add this option to the command line: `--transfer-info=@json:'{"ascp_args":["-DDL-"]}'`
This enables low level transfer logs on terminal, then locate the line:

```
LOG FASP Session Start uuid=1f693612-c941-4baa-b07a-598969e654cb op=recv status=failed errcode=40 errstr="Operation not permitted by license" source=/vol1/fastq/SRR123/036/SRR12397036/SRR12397036_2.fastq.gz dest=. source_prefix=- local=82.64.20.244:63463 peer=193.62.193.164:33001 tcp_port=33001 os="Darwin 23.3.0 Darwin Kernel Version 23.3" ver=4.4.3.891 ecd7192 lic=53:1:53 peeros="Linux 5.14.0-284.18.1.el9_2.x86_64 #1 SM" peerver=4.4.3.891 ecd7192 peerlic=0:0:0 proto_sess=20003 proto_udp=20000 proto_bwmeas=20000 proto_data=2000f
```

Notice the : `peerlic=0:0:0`
That usually means that the license file is not readable.

I suspect that the system was modified (upgrade, etc...), and the license file is not world-readable.

**Comment by Zhu-1998** [comment]
Hello, I had the same problem today. But yesterday, I could normally use `ascp` to download data from ena.
This is what I got today:



```
ascp -v -QT -l 500m -P33001 -k1 -i ~/.aspera/connect/etc/asperaweb_id_dsa.openssh --mode recv --host fasp.sra.ebi.ac.uk --user era-fasp --file-list filereport_read_run_PRJEB46177_tsv.txt ./fastq/

Session Stop  (Error: Failure processing peer license: Deprecated peer license)
``` 

Could you help me?

**Comment by mdehollander** [comment]
Super, I see in the biostars thread that Rasko Leinonen from EBI says:

> I have a received a word that a server side fix has been deployed. We have confirmed that e.g. ascp version 3.9.6 works once more.

I can confirm the ascp/ascli downloads from ena are working again.
