### ISSUE TITLE
Curl Method to download Aspera Share Files and folders using rest API

### ISSUE THREAD

**Issue by xavierv79** [IBM/aspera-cli#143]
Can we download Aspera shares using "curl " method. Is there any API for it.

**Comment by laurent-martin** [comment]
Hi,

No, IBM Aspera Shares does not provide an API or a method to download files using HTTP/S.

Transfers are exclusively with "FASP", IBM Aspera's accelerate file transfer protocol.

This is what this tool provides: `ascli shares files download ...`

Technically, it is possible to download with HTTPS, but that requires the use of an Aspera HTTP GW, and anyway, to call a few APIs en advance to get a transfer token, which `ascli` can also do.

**Comment by xavierv79** [comment]
Hi Laurent,

One of Our customer is Specifically asking for to download using CURL method  with https using Aspera HTTP GW. Please let us know for any possibilities.

**Comment by laurent-martin** [comment]
This is described here:

https://github.com/IBM/aspera-cli?tab=readme-ov-file#agent-http-gateway
