### ISSUE TITLE
Detailed steps to use rubyc to create sharable ascli executable

### ISSUE THREAD

**Issue by snps-djigande** [IBM/aspera-cli#149]
HI,
Would you please write down the different commands to execute to get first ascli, then get rubyc, then create a sharable ascli executable with rubyc. Please be as detailed as possible.  Please list all the different commands to run to create the ascli executable on LINUX first then on windows. But Linux first please.

**Comment by laurent-martin** [comment]
https://github.com/IBM/aspera-cli/issues/151
