### ISSUE TITLE
Needs example C++ using transfer spec V1 and directly the REST API of Shares

### ISSUE THREAD

**Issue by snps-djigande** [IBM/aspera-cli#155]
Hi

Do you by chance also have an example which use transfer spec V1 and directly the REST API of Shares to download a file too?
upload examples exist but do you have an example for download.

Thanks

**Comment by laurent-martin** [comment]
Yes, here:
https://github.com/laurent-martin/aspera-api-examples/blob/main/cpp/src/shares.cpp

In fact, it's better to open issues related to SDK examples here:
https://github.com/laurent-martin/aspera-api-examples/issues
