### ISSUE TITLE
support sending a folder/dir when using "--transfer=httpgw" flag

### ISSUE THREAD

**Issue by dremerten** [IBM/aspera-cli#156]
ascli currently does not support sending a folder when using httpgw, you need to provide the list of files.

Ask is to make this possible
```
/usr/local/rvm/gems/ruby-3.1.2/bin/ascli --transfer=httpgw --transfer-info=@json:'{"url":"https://qa-httpgw-proxy.example.com/aspera/http-gwy"}' faspex5 package send @json:"$json" **"$RANDOM_DIR" --**
```

**Comment by laurent-martin** [comment]
You can try the beta from here:

https://ibm.biz/aspera-cli-beta

**Comment by dremerten** [comment]
Yes, the beta gem is working for uploading Directories to httpGW 2.3.1

**Comment by laurent-martin** [comment]
So, next release should come soon.
