### ISSUE TITLE
Unable to download - ERROR: Argument: missing argument: identifier (String)

### ISSUE THREAD

**Issue by PietroD** [IBM/aspera-cli#158]
Hi

aspera-cli version 4.18.1

```
ascli faspex package recv \
--url=https://faspex.embl.de/aspera/faspex \
--user='xxx@xxx.it' \
--password='xxx' \
--id=ALL \
--once-only=yes \
--insecure=yes
```
 
```
ERROR: Argument: missing argument: identifier (String)
Use option -h to get help.
ERROR: Argument: unprocessed options: ["--id=ALL"]
```

I do not understand what the error is telling me. 
Thanks

**Comment by laurent-martin** [comment]
the `recv` command requires an argument.
To receive all packages, specify `ALL`.

https://github.com/IBM/aspera-cli?tab=readme-ov-file#automated-package-download-cargo

```
ascli faspex package recv ALL ...
```

option `id` is deprecated now, use positional argument instead.

see release notes:

https://github.com/IBM/aspera-cli/blob/main/CHANGELOG.md

Breaking Changes:

    global: Removed option id, deprecated since 4.14.0

**Comment by laurent-martin** [comment]
It used to be equivalent, but it was deprecated.
