### ISSUE TITLE
Need Aspera transfer SDK binaries (asperatransferd, ascp, ascp4) for Linux/aarch64

### ISSUE THREAD

**Issue by snps-djigande** [IBM/aspera-cli#161]
Hi Laurent,

Would please provide the different binaries (asperatransferd, ascp, ascp4, etc) needed to use Aspera transfer SDK on Linux/aarch64 in case IBM already has one.
If it is not yet available, would please tell me by when can we expect to get one from IBM?

Thanks a lot for your help

Kola

**Comment by laurent-martin** [comment]
Hi,

It will come soon, but the Transfer SDK is not part of the aspera-cli project.
It is part of the Official Aspera Transfer SDK here:
https://developer.ibm.com/apis/catalog/aspera--aspera-transfer-sdk/downloads/downloads.json

I think the plan is to have that before end of this year, but no commitment.

Internally, builds have been done on that platform, but not yet GA.

**Comment by snps-djigande** [comment]
Hi Laurent,

Thanks a lot for the update. Very good that linux aarch64 support is planed by end of the year.

Right, I received a Transfer SDK package from you which works fine for Linux and Windows.
I now need to integrate it on Linux aarch64 and realized there is no linux-aarch64 folder containing  asperatransferd, ascp and  ascp4. 

I got the C++ example as well as the SDK 1.1.3 package to compile and link on linux aarch64.

I would like to have early access to  the linux aarch64 packages of the Transfer SDK so that I can validate the integrate work early enough.
Any thing I should do/request to have early access of your internal beta version and provide feedback?

Thanks a lot.

Kola

**Comment by laurent-martin** [comment]
Hi,

You can find an `unofficial` build here:

https://eudemo.asperademo.com/download/linux-arm64.zip

Important:

This is not to be used in any production system, as it has not gone through official validation.
IBM will not provide any support for that build.
Use at your own risk, only for validation in dev environment.

I have tested it , though, on Rocky Linux 9 on arm64, with python samples from : https://github.com/laurent-martin/aspera-api-examples as well as with a basic transfer with ascli.

```
Linux localhost.localdomain 5.14.0-427.35.1.el9_4.aarch64 #1 SMP PREEMPT_DYNAMIC Thu Sep 12 15:25:36 EDT 2024 aarch64 aarch64 aarch64 GNU/Linux
```

To install in ascli:

```bash
ascli conf ascp install --sdk-url=https://eudemo.asperademo.com/download/linux-arm64.zip
```

Hopefully, IBM will officially release a fully validated SDK one day.

**Comment by snps-djigande** [comment]
Hi Laurent,

I seem to be missing the required license to execute the asyn executable for Linux aarch64 (License does not allow async use).
Please help. I have been using the same license file I got for linux and windows.
Thanks

> trsdk/linux-arm64/async --version
async version 4.4.5.1620 ca02014
Operating System: Linux
License does not allow async use
Invalid license direction field



while ascp is OK
> trsdk/linux-arm64/ascp --version
Product version information not found.
ascp version 4.4.5.1620 ca02014
Operating System: Linux
License max rate=(unlimited), account no.=1, license no.=56
Enabled settings: stream


asperatransferd.log does not tell too much:

{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: Config: ({\n \"LogDirectory\": \"/tmp\",\n \"LogLevel\": \"4\",\n \"Address\": \"127.0.0.1\",\n \"Port\": 55002,\n \"Reflection\": false,\n \"Workers\": {\n  \"MaxConcurrent\": 100,\n  \"TransferCleaningPeriod\": 3600,\n  \"TransferMaxAge\": 7200\n },\n \"FaspManagementConfig\": {\n  \"PromiscuousModeEnabled\": false,\n  \"Port\": 0,\n  \"Address\": \"127.0.0.1\"\n },\n \"FaspRuntime\": {\n  \"UseEmbedded\": false,\n  \"ForceVersion\": \"4.4.1\",\n  \"UserDefined\": {\n   \"Bin\": \"/trsdk/linux-arm64\",\n   \"Etc\": \"/trsdk/etc\"\n  },\n  \"FaspLog\": {\n   \"Dir\": \"/tmp\",\n   \"Level\": 2\n  },\n  \"ExtraConfig\": null\n },\n \"TLS\": {\n  \"Enabled\": false,\n  \"Certificate\": \"\",\n  \"Key\": \"\",\n  \"MinTLSVersion\": \"\"\n },\n \"Authentication\": {\n  \"Enabled\": false,\n  \"APIKey\": \"\"\n },\n \"APITimeout\": {\n  \"MaxConnectionIdle\": 86400,\n  \"MaxConnectionAge\": 0,\n  \"MaxConnectionAgeGrace\": 0,\n  \"Time\": 7200,\n  \"Timeout\": 20\n },\n \"InstallationPath\": \"/trsdk/linux-arm64\"\n})","time":"2024-09-26T16:12:12+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: TransferManager: binary path found /trsdk/linux-arm64","time":"2024-09-26T16:12:12+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: TransferManager: server info {\n \"ManagementPort\": 0,\n \"AsperaInfo\": [\n  {\n   \"AsperaBinary\": \"ascp\",\n   \"AsperaVersion\": \"4.4.5.1620 ca02014\",\n   \"OperatingSystem\": \"Linux\",\n   \"Error\": null\n  },\n  {\n   \"AsperaBinary\": \"ascp4\",\n   \"AsperaVersion\": \"4.4.5.1620 ca02014\",\n   \"OperatingSystem\": \"Linux\",\n   \"Error\": null\n  },\n  {\n   \"AsperaBinary\": \"async\",\n   \"AsperaVersion\": \"4.4.5.1620 ca02014\",\n   \"OperatingSystem\": \"Linux\",\n   \"Error\": null\n  }\n ],\n \"LicenseInfo\": {\n  \"MaxRate\": \"unlimited\",\n  \"AccountNumber\": \"1\",\n  \"LicenseNumber\": \"56\",\n  \"License\": \"\\u003clicense version=\\\"1\\\"\\u003e\\r\\n  \\u003c!-- Void if modified --\\u003e\\r\\n  \\u003cproduct_id\\u003e56\\u003c/product_id\\u003e\\r\\n  \\u003ccustomer_id\\u003e1\\u003c/customer_id\\u003e\\r\\n  \\u003clicense_id\\u003e56\\u003c/license_id\\u003e\\r\\n  \\u003caccounts\\u003e0\\u003c/accounts\\u003e\\r\\n  \\u003cunique_concurrent_logins\\u003e0\\u003c/unique_concurrent_logins\\u003e\\r\\n  \\u003cmaximum_bandwidth\\u003eunlimited\\u003c/maximum_bandwidth\\u003e\\r\\n  \\u003cexpiration_date\\u003enone\\u003c/expiration_date\\u003e\\r\\n  \\u003cconnect_enabled\\u003eno\\u003c/connect_enabled\\u003e\\r\\n  \\u003chttp_fallback_server_enabled\\u003eno\\u003c/http_fallback_server_enabled\\u003e\\r\\n  \\u003cgroup_configuration_enabled\\u003eno\\u003c/group_configuration_enabled\\u003e\\r\\n  \\u003cshared_endpoints_enabled\\u003eno\\u003c/shared_endpoints_enabled\\u003e\\r\\n  \\u003cdesktop_gui_enabled\\u003eno\\u003c/desktop_gui_enabled\\u003e\\r\\n  \\u003cstream_enabled\\u003eyes\\u003c/stream_enabled\\u003e\\r\\n\\u003c/license\\u003e\"\n },\n \"PromiscuousMode\": false\n}","time":"2024-09-26T16:12:12+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: TransferManager: checked ascp version successfuly against 4.4.1","time":"2024-09-26T16:12:12+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: TransferManager: checked ascp4 version successfuly against 4.4.1","time":"2024-09-26T16:12:12+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: TransferManager: checked async version successfuly against 4.4.1","time":"2024-09-26T16:12:12+02:00"}

Thanks

Kola

**Comment by laurent-martin** [comment]
Use the license file provided in one of the official Transfer SDK archives version 1.1.3

**Comment by snps-djigande** [comment]
Thanks Laurent. Got one and used it. 
Now the async license issue is solved but still asperatransferd exists right away without any noticeable error message (in lining the entire  content of the /asperatransferd.log).



>trsdk/linux-arm64/async --version
async version 4.4.5.1620 ca02014
Operating System: Linux
License max rate=(unlimited), account no.=1, license no.=56
License allows ALL session directions (PUSH, PULL, or BIDI)
----------------------------------------------------------------------------

>cat  asperatransferd.log
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: Config: ({\n \"LogDirectory\": \"/tmp\",\n \"LogLevel\": \"4\",\n \"Address\": \"127.0.0.1\",\n \"Port\": 55002,\n \"Reflection\": false,\n \"Workers\": {\n  \"MaxConcurrent\": 100,\n  \"TransferCleaningPeriod\": 3600,\n  \"TransferMaxAge\": 7200\n },\n \"FaspManagementConfig\": {\n  \"PromiscuousModeEnabled\": false,\n  \"Port\": 0,\n  \"Address\": \"127.0.0.1\"\n },\n \"FaspRuntime\": {\n  \"UseEmbedded\": false,\n  \"ForceVersion\": \"4.4.1\",\n  \"UserDefined\": {\n   \"Bin\": \"/trsdk/linux-arm64\",\n   \"Etc\": \"/trsdk/etc\"\n  },\n  \"FaspLog\": {\n   \"Dir\": \"/tmp\",\n   \"Level\": 2\n  },\n  \"ExtraConfig\": null\n },\n \"TLS\": {\n  \"Enabled\": false,\n  \"Certificate\": \"\",\n  \"Key\": \"\",\n  \"MinTLSVersion\": \"\"\n },\n \"Authentication\": {\n  \"Enabled\": false,\n  \"APIKey\": \"\"\n },\n \"APITimeout\": {\n  \"MaxConnectionIdle\": 86400,\n  \"MaxConnectionAge\": 0,\n  \"MaxConnectionAgeGrace\": 0,\n  \"Time\": 7200,\n  \"Timeout\": 20\n },\n \"InstallationPath\": \"/trsdk/linux-arm64\"\n})","time":"2024-09-26T17:42:09+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: TransferManager: binary path found /trsdk/linux-arm64","time":"2024-09-26T17:42:09+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: TransferManager: server info {\n \"ManagementPort\": 0,\n \"AsperaInfo\": [\n  {\n   \"AsperaBinary\": \"ascp\",\n   \"AsperaVersion\": \"4.4.5.1620 ca02014\",\n   \"OperatingSystem\": \"Linux\",\n   \"Error\": null\n  },\n  {\n   \"AsperaBinary\": \"ascp4\",\n   \"AsperaVersion\": \"4.4.5.1620 ca02014\",\n   \"OperatingSystem\": \"Linux\",\n   \"Error\": null\n  },\n  {\n   \"AsperaBinary\": \"async\",\n   \"AsperaVersion\": \"4.4.5.1620 ca02014\",\n   \"OperatingSystem\": \"Linux\",\n   \"Error\": null\n  }\n ],\n \"LicenseInfo\": {\n  \"MaxRate\": \"unlimited\",\n  \"AccountNumber\": \"1\",\n  \"LicenseNumber\": \"56\",\n  \"License\": \"\\u003clicense version=\\\"1\\\"\\u003e\\r\\n  \\u003c!-- Void if modified --\\u003e\\r\\n  \\u003cproduct_id\\u003e56\\u003c/product_id\\u003e\\r\\n  \\u003ccustomer_id\\u003e1\\u003c/customer_id\\u003e\\r\\n  \\u003clicense_id\\u003e56\\u003c/license_id\\u003e\\r\\n  \\u003caccounts\\u003e0\\u003c/accounts\\u003e\\r\\n  \\u003cunique_concurrent_logins\\u003e0\\u003c/unique_concurrent_logins\\u003e\\r\\n  \\u003cmaximum_bandwidth\\u003eunlimited\\u003c/maximum_bandwidth\\u003e\\r\\n  \\u003cexpiration_date\\u003enone\\u003c/expiration_date\\u003e\\r\\n  \\u003cconnect_enabled\\u003eno\\u003c/connect_enabled\\u003e\\r\\n  \\u003chttp_fallback_server_enabled\\u003eno\\u003c/http_fallback_server_enabled\\u003e\\r\\n  \\u003cgroup_configuration_enabled\\u003eno\\u003c/group_configuration_enabled\\u003e\\r\\n  \\u003cshared_endpoints_enabled\\u003eno\\u003c/shared_endpoints_enabled\\u003e\\r\\n  \\u003cdesktop_gui_enabled\\u003eno\\u003c/desktop_gui_enabled\\u003e\\r\\n  \\u003cstream_enabled\\u003eyes\\u003c/stream_enabled\\u003e\\r\\n  \\u003csync2\\u003e\\r\\n    \\u003cenabled\\u003eyes\\u003c/enabled\\u003e\\r\\n    \\u003cdirection\\u003ebidi\\u003c/direction\\u003e\\r\\n    \\u003cmaximum_files\\u003eunlimited\\u003c/maximum_files\\u003e\\r\\n  \\u003c/sync2\\u003e\\r\\n\\u003c/license\\u003e\"\n },\n \"PromiscuousMode\": false\n}","time":"2024-09-26T17:42:09+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: TransferManager: checked ascp version successfuly against 4.4.1","time":"2024-09-26T17:42:09+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: TransferManager: checked ascp4 version successfuly against 4.4.1","time":"2024-09-26T17:42:09+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: TransferManager: checked async version successfuly against 4.4.1","time":"2024-09-26T17:42:09+02:00"}

**Comment by laurent-martin** [comment]
Which Linux distribution and version are you using?

**Comment by snps-djigande** [comment]
Hi Laurent,

I am using the following version

Thanks

Kola

LSB Version:    :core-4.1-aarch64:core-4.1-noarch:cxx-4.1-aarch64:cxx-4.1-noarch:desktop-4.1-aarch64:desktop-4.1-noarch:languages-4.1-aarch64:languages-4.1-noarch:printing-4.1-aarch64:printing-4.1-noarch
Distributor ID: AlmaLinux
Description:    AlmaLinux release 8.4 (Electric Cheetah)
Release:        8.4
Codename:       ElectricCheetah

**Comment by laurent-martin** [comment]
I have installed alma linux 8.4 on aarch64, and asperatransferd works well there.

**Comment by laurent-martin** [comment]
Well, first, I think that the transfer SDK doc is wrong:
![image](https://github.com/user-attachments/assets/d6d22b1e-61cb-49f2-a1fb-6328f0b22a02)

log_level is a string with a value in:

```console
trace debug info warning error fatal panic
```

and I see you set the level to "6", which is ignored, so, set this to `trace` in your config file.

You should get maybe more information on why it exits. it does not for me.

I see also you use port zero, I have added some code here to show how to use port zero and read from log file, although it's not a good solution for long term:

https://github.com/laurent-martin/aspera-api-examples/blob/main/python/src/utils/transfer_client.py#L120

I see also you set the ascp log level to 6 (int), maximum is 2.

here my conf file:

```json
{
  "address": "localhost",
  "port": 0,
  "log_directory": "/tmp",
  "log_level": "trace",
  "fasp_runtime": {
    "use_embedded": false,
    "user_defined": {
      "bin": "/home/laurent/aspera-api-examples/tmp/trsdk/linux-arm64",
      "etc": "/home/laurent/aspera-api-examples/tmp/trsdk/noarch"
    },
    "log": {
      "dir": "/tmp",
      "level": 0
    }
  }
}
```

**Comment by snps-djigande** [comment]
Hi Laurent,
Using "trace" as log_level  in the config file did not give me more output
asperatransferd exists with 1 status without any error message in the log file.

Is it possible to get a debug version of asperatransferd or a more verbose?
Should I send you the aspera-license file I am using?

On a CentOS version of arm64 I have the same problem.

Thanks

Kola

**Comment by laurent-martin** [comment]
Please share the folder structure you are using (what is located in PATH/trsdk/linux-arm64 and other folders) and the content of the config file.

I have this:

```json
{
  "address": "localhost",
  "port": 0,
  "log_directory": "/tmp",
  "log_level": "trace",
  "fasp_runtime": {
    "use_embedded": false,
    "user_defined": {
      "bin": "/home/laurent/aspera-api-examples/tmp/sdk_runtime",
      "etc": "/home/laurent/aspera-api-examples/tmp/sdk_runtime"
    },
    "log": {
      "dir": "/tmp",
      "level": 0
    }
  }
}
```

and here the content of: `/home/laurent/aspera-api-examples/tmp/sdk_runtime` :

```
ascp
ascp4
aspera.conf
aspera-license
asperatransferd
async
libafwsfeed.so
product-info.mf

```

**Comment by snps-djigande** [comment]
Hi Laurent,

I do have the following:


trsdk
├── etc
│   ├── aspera.conf
│   └── aspera-license
└── linux-arm64
    ├── ascp
    ├── ascp4
    ├── asperatransferd
    ├── async
    └── libafwsfeed.so

And config file:
{"address":"localhost","port":55002,"log_directory":"/tmp","log_level":"trace","fasp_runtime":{"use_embedded":false,"user_defined":{"bin":"<PATH>/trsdk/linux-arm64","etc":"<PATH>/trsdk/etc"},"log":{"dir":"/tmp","level":2}}}


I do not have product-info.mf. It is needed?

Thanks

Kola

**Comment by laurent-martin** [comment]
`product-info.mf` is optional, it is not required.

Ok, we have almost the same, except, I have all in the same folder, but ascp/ascp4 can accomodate this.

**Comment by snps-djigande** [comment]
I copied the content of etc in linux-arm64 and pointed etc to linux-arm64 in conf file.
Still log file has no error and exits status is 1.
What a bout providing an instrumented asperatransferd file?

Thanks

Kola

**Comment by laurent-martin** [comment]
There is no instrumented bin.

Do you start the daemon on command line in a terminal ?

If there is an error, it displays in stdout / stderr.

**Comment by snps-djigande** [comment]
Yes, that's all I did:
Could be that we are not using the same aspera-license file?
I would highly like to get that working as soon as possible.

%/trsdk/linux-arm64/asperatransferd -c _full_path/asperatransferd.conf 
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: Loaded config from _full_path/asperatransferd.conf","time":"2024-09-30T14:44:34+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: Installation path : (_my_path/trsdk/linux-arm64) logFile (/tmp/asperatransferd.log)","time":"2024-09-30T14:44:34+02:00"}
2024/09/30 14:44:34 exit status 1

**Comment by laurent-martin** [comment]
Try to run ascp4 like this:

```bash
ASPERA_TEST_REDIS_DISABLE=true _full_path/ascp4 -h
```

It should display ascp4 help

**Comment by snps-djigande** [comment]
Yes, that works:

env ASPERA_TEST_REDIS_DISABLE=true _path/trsdk/linux-arm64/ascp4 -h
Usage: ascp4 [OPTION] SRC... DEST
          SRC to DEST, or multiple SRC to DEST dir
          SRC, DEST format: [[user@]host:]PATH
  -h,--help                       Display usage
  -A,--version                    Display version.
  -T                              Disable encryption
  -p                              Preserve file timestamp
  -q                              Disable progress display
  -D...                           Debug level
  -l MAX-RATE                     Max transfer rate
  -m MIN-RATE                     Min transfer rate
                                  RATE: G/g(gig),M/m(meg),K/k(kilo)
  -i PRIVATE-FILE                 Private key file
  -Z DGRAM-SIZE                   Manually set MTU
  -L LOCAL-LOG-DIR                Local logging dir
  -R REMOTE-LOG-DIR               Remote logging dir
  -O FASP-PORT                    UDP port used by FASP
  -P SSH-PORT                     TCP port used by SSH
  -N PATTERN                      Inclusion pattern. Repeat for more.
  -E PATTERN                      Exclusion pattern. Repeat for more.
  -f CONFIG-FILE                  Configuration-file name
  --chunk-size=BYTES              Buffer size used for storage read/write operations (limited to 128M)
  --mode=MODE                     MODE: send, recv
  --faspmgr-io
  --user=USERNAME
  --host=HOSTNAME
  --memory=MAX_MEMORY             Max memory for IO operations
  --remote-memory=MAX_MEMORY      Max memory for IO operations on remote machine
  --policy=TRANSFER_POLICY        TRANSFER_POLICY: fixed,high,fair,low
  --file-list=FILENAME
  --file-pair-list=FILENAME
  --apply-local-docroot           Apply local docroot
  --overwrite=METHOD              METHOD: never,always,diff,diff+older,older
  --compare=METHOD                METHOD: size,size+mtime,md5,md5-sparse,sha1,sha1-sparse
  --resume
  --src-base=NAME                 Preserve directory structure of SRC
                                  arguments below NAME (send mode only)
  --proxy=URL
  --preserve-file-owner-uid
  --preserve-file-owner-gid
  --preserve-xattrs=MODE          MODE: native,metafile,none
  --remote-preserve-xattrs=MODE   MODE: native,metafile,none
  --preserve-acls=MODE            MODE: native,metafile,none
  --remote-preserve-acls=MODE     MODE: native,metafile,none
  --sparse-file
  --read-threads=NUM              Number of storage "read" threads (default 2)
  --write-threads=NUM             Number of storage "write" threads (default 2)
  --scan-threads=NUM              Number of directory "scanning" threads (default 2)
  --meta-threads=NUM              Number of meta "creating" threads (default 1)
  --crypt-threads=NUM             Number of crypt threads (default 1)
  --compression=METHOD            METHOD can be one of: none, zlib, or lz4.
                                                        (Default lz4)
  --compression-hint=NUM          Compression level for zlib: integer from -1 to 9
                                                              (Default -1)
  --file-crypt=WHICH              Either "encrypt" or "decrypt"
  --fail-bad-filepass             Fail on bad file decryption passphrase
  --exclude-older-than=MTIME      Skip src files with mtime < MTIME
  --exclude-newer-than=MTIME      Skip src files with mtime > MTIME
  --delete-before                 Deletes files in destination that don't exist in source before transfer starts
  --check-sshfp=FINGERPRINT       Required server SSH host key fingerprint

  --precalculate-job-size
  --precalculate-disable
  --file-checksum=HASH            HASH: sha-512,sha-384,sha-256,sha1,md5,none
  --remove-after-transfer         Remove SRC files after transfer success
  --remove-skipped                Remove skipped SRC files after transfer
  --symbolic-links                Handle symbolic links using the specified METHOD. METHOD can be: follow or                                  skip on Windows. On other operating systems, METHOD can be: copy,                                  copy + force, follow or skip. Default is follow.  --move-after-transfer=ARCHIVE   Move SRC files under path ARCHIVE after transfer success
  --partial-file-suffix=SUFFIX    To override the config option
  --remove-empty-directories      Remove empty SRC subdirectories
  --remove-empty-source-directory Also remove the source directory itself if empty
  --source-prefix                 Prepend to each SRC path
  --source-prefix64               Base64 encoded source-prefix, prepend
                                  to each SRC path

**Comment by snps-djigande** [comment]
Hi Laurent

By instrumented asperatransferd, I mean an executable with more fprintf debug messages to find out at which step the executable exits and why. This extra debug message can be protected by an environment variable.

In  asperatransferd,log I see MaxConnectionAge\": 0
Is a 0 value expeceted here? if not how can I set a different value.

Would you please send me the exact license file you are using. The one I grabbed from the internet might be different.

Thanks

Kola

**Comment by laurent-martin** [comment]
You shall use the license file from SDK available in any of those packages:
https://developer.ibm.com/apis/catalog/aspera--aspera-transfer-sdk/downloads/downloads.json

**Comment by snps-djigande** [comment]
<license_id>56</license_id>

Ok, this where I got the license file I am using.

**Comment by snps-djigande** [comment]
If I compare the log files of x86_64 versus aarch64 I see that x86_64 does have "corpus store loaded" message which does not happen for aarch64

{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"debug","msg":"Debug: TransferManager: corpus store loaded","time":"2024-10-01T14:51:56+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: ConnectionManager: FaspManager listening on 127.0.0.1:39231","time":"2024-10-01T14:51:56+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: TransferWorkerScheduler started","time":"2024-10-01T14:51:56+02:00"}



For aarch64, I instead get the following 3 last lines:

{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: TransferManager: checked ascp version successfuly against 4.4.1","time":"2024-10-01T14:59:54+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: TransferManager: checked ascp4 version successfuly against 4.4.1","time":"2024-10-01T14:59:54+02:00"}
{"appname":"faspmanagerd","hostname":"127.0.0.1","level":"info","msg":"Info: TransferManager: checked async version successfuly against 4.4.1","time":"2024-10-01T14:59:54+02:00"}

**Comment by snps-djigande** [comment]
Hi Laurent,

Any update?
This issue is blocking me right now.
Would you please reopen the issue - it is currently marked as closed.
Thanks a lot for your help.
Kola

**Comment by snps-djigande** [comment]
Hi Laurent,

Any update?
This issue is blocking me right now.
Would you please reopen the issue - it is currently marked as closed.
Would you please attach a customer label on it.
Thanks a lot for your help.
Kola

**Comment by laurent-martin** [comment]
Please send an email directly: laurent.martin.aspera at fr.ibm.com

**Comment by laurent-martin** [comment]
Ok, so finally, we found the culprit: `async`

So a workaround is: overwrite the `async` binary with `ascp`, that will make asperatransferd happy, as you are using only ascp.

**Comment by snps-djigande** [comment]
Yes,
Thanks you very much Laurent for your time and very useful help

Kola
