### ISSUE TITLE
Cannot start a new asperatransferd process if one already exists on Linux. On Windows this works.

### ISSUE THREAD

**Issue by snps-djigande** [IBM/aspera-cli#162]
Hi Laurent

On windows, I can run an asperatransferd.exe even if an old process is visible in process explorer but on Linux this does not work for me, the child process is nor running.
Could it be related to the grpc port? or licensing?
Please help

Thanks

Kola

**Comment by laurent-martin** [comment]
First, this repo is about `ascli`, not the transfer SDK.
Normazlly, use the IBM support for such questions.

`asperatransferd` (Transfer SDK) listens on a TCP port, if this port is already used, then it exits.

The value of the port itself is not very important, it can be any available port, and then the gRPC client must use it.
One way it to tell asperatransferd to use port 0 (zero), and then get the actual value from its log, but it is not very reliable (if log changes).
I have already opened a enhancement ticket on that aspect.

**Comment by snps-djigande** [comment]
Thanks for Laurent for the quick answer.
Very useful
Please keep me posted when the enhancement is done.

Thanks

Kola

**Comment by laurent-martin** [comment]
There is no enhancement planned so far.
