### ISSUE TITLE
[Win] After transfer, asked to "Terminate batch job (Y/N)?"

### ISSUE THREAD

**Issue by willgcho** [IBM/aspera-cli#22]
### Environment

* ascli 4.0.0.pre2
* Win10 x64, ruby 2.7.2p137

### Description

With Windows ascli, after every transfer I get prompted with "Terminate batch job (Y/N)?". It doesn't seem to matter what I enter; the command finishes running whether I enter 'y' or 'n'. Maybe this issue is specific to Windows command prompt? Would be good if this prompt could be removed.

    C:\Users\WDAGUtilityAccount\Downloads>ascli faspex --url=https://10.0.213.232/aspera/faspex --insecure=yes --user=*** --password=*** package recv --id=21281
    200KB.100                                     100%  200KB  2.2Mb/s    00:00
    Completed: 200K bytes transferred in 0 seconds
     (1974K bits/sec), in 1 file, 1 directory.
    ^CTerminate batch job (Y/N)? y

    C:\Users\WDAGUtilityAccount\Downloads>

### Notes

* Linux (and presumably Mac) ascli does not have this issue with the unexpected "Terminate batch job" prompt.
* Not an issue with ascli commands that don't involve transfers (ex: browse, apiinfo).

**Comment by laurent-martin** [comment]
I have also seen this with a customer.

**Comment by laurent-martin** [comment]
fixed in "develop" branch, so will be in next version (one can try by just copying the file: local.rb )
