### ISSUE TITLE
Password not obfuscated when entered interactively

### ISSUE THREAD

**Issue by willgcho** [IBM/aspera-cli#23]
### Environment

* ascli 4.0.0.pre1
* Debian 9.13 x64, ruby 3.0.0p0
* Win10 x64, ruby 2.7.2p137

### Description

Noticed the password is not obfuscated when entering it interactively using --interactive=yes.

    C:\Users\WDAGUtilityAccount\Downloads>ascli node --url=https://10.0.213.232:9092 --username=asdf --interactive=yes license
    option: password> asdf
    ERROR: Rest: 10.0.213.232:9092 401 Unauthorized

The test case I was using listed for its expected result "Password is hidden when typed". This test case was for the old cli, I think, and perhaps not relevant to the newer ascli. Do we still expect for the password to be obfuscated in this case?

**Comment by laurent-martin** [comment]
good catch, easy to fix using:
require 'io/console'
STDIN.getpass("Password:")
Also, sensitive information (such as passwords, keys) need to be identified when declared, so that mechanism is automated.
