### ISSUE TITLE
We should run UTs in both Ruby 2.4 and 3.0 environments

### ISSUE THREAD

**Issue by gegles** [IBM/aspera-cli#28]
> In terms of validation, we should validate on both : 2.4 and 3.0
> (I was testing on 3.7 previously, but moved to 3.0 because shell had installed this)
> (in a simple environment, rvm can install multiple versions for validation)

@willgcho great if you can add that to your test matrix. We could also try to have some automation around this here in GitHub Actions and test in 2 environments (@dwosk ?)

_Originally posted by @gegles in https://github.com/IBM/aspera-cli/issues/27#issuecomment-763821957_

**Comment by dwosk** [comment]
I have a matrix setup in the `ruby-matrix` branch but there's a race condition - both unit tests touch the same files on the server at the same time, causing one to pass but the other to fail.
