### ISSUE TITLE
Set up GitHub Actions to release & publish to Rubygems.org

### ISSUE THREAD

**Issue by gegles** [IBM/aspera-cli#3]
For example, leverage the [Publish to Rubygems](https://github.com/marketplace/actions/publish-to-rubygems) GitHub action.

Not sure how much can be tested prior to release.

Not sure what the best release trigger is (see best practice). Maybe this happens automatically when we push to `main` branch.

Ideally a version gets bumped, the repo tagged and the gem + doc gets published.

**Comment by dwosk** [comment]
Created action to run unit tests: https://github.com/IBM/aspera-cli/commit/d2c2728527815e5531a981bb5f68be2dcf0f4c8f
