### ISSUE TITLE
Feature or documentation How to migrate from older mlia   

### ISSUE THREAD

**Issue by m67hoff** [IBM/aspera-cli#31]
It would be really helpful to get a migration hint or tool from the older versions.

**Comment by gegles** [comment]
Thanks @m67hoff ! In theory, it should really just be a renaming of the various package names and binaries, but I agree we should at least put a little section in the doc explaining that. thx.

**Comment by laurent-martin** [comment]
Michael, do you mean migration from tool `aspera` or from `mlia`?

Notes:
`ascli` detects when it is first executed and migrates configuration from `mlia` automatically.
`ascli` can export its configuration to `aspera`, but not yet the way around: it can be added.

**Comment by m67hoff** [comment]
yes - from mlia to ascli.  ( I have lots of access credentials only in config.yaml  )

**Comment by gegles** [comment]
> rom mlia to ascli. ( I have lots of access credentials only in config.yaml

@m67hoff, it appears what you are asking for (`mlia` -> `ascli`) is already in. Let us know if this addresses your concern (or close the issue) or if there is more to be done. thx!

**Comment by laurent-martin** [comment]
code is here:
https://github.com/IBM/aspera-cli/blob/develop/lib/aspera/cli/plugins/config.rb#L279
