### ISSUE TITLE
Feature Request - Package Status Checker

### ISSUE THREAD

**Issue by cjplay02** [IBM/aspera-cli#35]
Get Packages AoC API - https://developer.ibm.com/apis/catalog/aspera--aspera-on-cloud-api/api/API--aspera--aspera-on-cloud-api#get_packages

Is this or can this be in the Aspera CLI Executable?  We need to ping AoC to see if a package is still transferring and/or is completed before attempting to pull it.

**Comment by laurent-martin** [comment]
use the command:
`ascli aoc admin resource package`
you can `list` (with filtering options) and `show` (a particular package)
output can be in any supported format (text table, csv, json, etc..)
and fields can be filtered.

**Comment by gegles** [comment]
@cjplay02 , let us know if what @laurent-martin suggested solves your issue or if there still is a gap. Thanks!
