### ISSUE TITLE
Feature Request - Rename Package 

### ISSUE THREAD

**Issue by cjplay02** [IBM/aspera-cli#36]
AoC API - https://developer.ibm.com/apis/catalog/aspera--aspera-on-cloud-api/api/API--aspera--aspera-on-cloud-api#update_package

Can we get the CLI executable to have update package so we can rename it?  We forward packages that come in rather than move them to save time, but the input name may not be contextually relevant to the second recipient.  Therefore, we need a way to rename the package before changing the recipients and forwarding.

**Comment by laurent-martin** [comment]
the command:
`ascli aoc amdin resource package`  has the sub command `modify`

**Comment by cjplay02** [comment]
Please confirm “amdin” is really “admin”?  If this works, then thank you very much!

Thank you,
Chris.Henderson@warnerbros.com<mailto:Chris.Henderson@warnerbros.com>
WAMO - Cell: 714-520-1905; Desk: 818-977-4320
Bldg 168/Pinnacle II, Rm 5319

**Comment by laurent-martin** [comment]
I checked that the AoC API does not allow to rename an already sent package:
```
ascli aoc admin res pack --id=HxzZAKbNwi modify @json:'{"name":"new name"}'

ERROR: Rest: found unpermitted parameter: :name
code: unpermitted_parameters
request_id: 1b6afbbe-28de-4d71-b112-a9751c7fb26a
api.ibmaspera.com 422 Unprocessable Entity
```
Not a limitation of the CLI, but it's by design of AoC
