### ISSUE TITLE
QUESTION - AoC Workspace Member List

### ISSUE THREAD

**Issue by cjplay02** [IBM/aspera-cli#40]
I want a succinct list of users that are a member of my or another's workspace.  I've tried variations of this - 
```
ascli aoc admin user resource list --workspace="<redacted>"
```
with no luck.  Still trying, but any ideas would be helpful.

**Comment by cjplay02** [comment]
Got a lot closer with this example from the CLI Rubydoc, but it only lists some of the members of the workspace.  Only shows 6 users/groups, 2 groups have no name showing, and none of the inherited users.  Still working on it.

ascli aoc admin res workspace_membership list --fields=member_type,manager,member.email --query=@json:'{"page":1,"per_page":50,"embed":"member","inherited":true,"workspace_id":redacted,"sort":"name"}'

**Comment by gegles** [comment]
@laurent-martin any guidance for @cjplay02 here?

**Comment by laurent-martin** [comment]
Hi, by "inherited" you wants to list also members of groups who belong to the workspace, right ?

**Comment by cjplay02** [comment]
Correct.  Thank you.

Thanks, ***@***.***
________________________________

**Comment by laurent-martin** [comment]
Question answered.
