### ISSUE TITLE
"ascli config ascp use" won't accept a windows path to ascp.exe

### ISSUE THREAD

**Issue by bruceoberg** [IBM/aspera-cli#43]
i have an extant installation of ascp on my win 10 machine. after installing the aspera-cli gem, i want to point ascli at my existing ascp installation. here's my first try and the response:
```
C:\>ascli config ascp use g:\ip4r\extern\aspera\bin\aspera.exe
ERROR: Other: file name must be ascp
Use '--log-level=debug' to get more details.
```
ok. maybe it doesn't want to see the .exe in the name? next i try:
```
C:\>ascli config ascp use g:\ip4r\extern\aspera\bin\ascp
ERROR: Other: no such file: g:\ip4r\extern\aspera\bin\ascp
Use '--log-level=debug' to get more details.
```
hmmm. ascli is pretty picky about this file existing and having a particular name. i'll go hardlink the `ascp.exe` file to one named `ascp` and try again:
```
C:\>ascli config ascp use g:\ip4r\extern\aspera\bin\ascp
ERROR: Other: not executable: g:\ip4r\extern\aspera\bin\ascp
Use '--log-level=debug' to get more details.
```
so has anyone ever convinced ascli to use a extant windows ascp install?

here are my versions of everything:

- windows 10 
- ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]
- ascli 4.1.0
- ascp version 3.9.6.177525

**Comment by laurent-martin** [comment]
Read this:
