### ISSUE TITLE
Transfer of bigger files (10 TB) using ascli is too slow with 10 % data loss

### ISSUE THREAD

**Issue by sujata00** [IBM/aspera-cli#44]
I attempted to transfer 10 TB file to server using the below command on a VM by logging in as root user:

```
ascli cos -N --bucket=pr-bucket1 --endpoint=https://s3.jp-tok.cloud-object-storage.appdomain.cloud --apikey=0txTzHFDuCfGY0wLp2Z5U1cjQ82AAR3PC0odHALsyxv3 --crn=crn:v1:bluemix:public:cloud-object-storage:global:a/96f925a37d236c8abd126579c5abb214:7a0069c7-be61-40b9-9b14-21bbacb1eee7:: node upload 10TB.txt --ts=@json:'{"target_rate_kbps":1000000,"resume_policy":"sparse_csum"}'
```

The command worked fine, but the transfer rate is too slow in comparison to AWS. It is taking around 48 hours to transfer 10 TB file.

<b> When the same file was transferred using AWS service it took around 22 Hours to complete the transfer <b>

**Comment by laurent-martin** [comment]
This makes an average speed of 460 Mbps.
You may look at limits:
[https://ibmaspera.com/help/transfer_service/getting_started-2/cloud_platforms_and_regions_supported](https://ibmaspera.com/help/transfer_service/getting_started-2/cloud_platforms_and_regions_supported)

You may try to use multi-session like this:
[https://github.com/IBM/aspera-cli#support-of-multi-session](https://github.com/IBM/aspera-cli#support-of-multi-session)

```
--ts=@json:'{"multi_session":5,"multi_session_threshold":1,"resume_policy":"none"}'
```

One can analyse the log files generated by ascp, on Linux it is logged to syslog facility `local2`

**Comment by cjplay02** [comment]
AWS does not support a single file >5TB.  This is publicly documented here - https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html

**Comment by laurent-martin** [comment]
I guess this can be closed
