### ISSUE TITLE
Packages within a Shared Inbox or Dropbox?

### ISSUE THREAD

**Issue by cjplay02** [IBM/aspera-cli#47]
https://api.asperafiles.com/api/v1/packages?dropbox_id=5322 - This API call to AoC gets me a list of packages sent to the inbox of a workspace, but I need to know the box ID's in my workspace first.  So, how can I do this in ascli?  We tried for 3 hours even using query/value JSONs for the "recipients" array and just cannot seem to find and/or format it correctly.

Use case?  My workspaces have multiple dropboxes and I need to only pull new packages within a single box.  However, I cannot seem to isolate the packages list to the box I want.

UX?  I'd love a --dropbox="name of box" option, or at least a --dropbox_id=1234 switch added to the packages list command.

**Comment by laurent-martin** [comment]
Did you test it ?
