### ISSUE TITLE
Upload of file failing through Aspera CLI

### ISSUE THREAD

**Issue by nikkuc01** [IBM/aspera-cli#62]
Our customer is trying to upload a 14GB file through Aspera CLI. After taking more than 3 hours, it's showing 100% but package_id is not generated. Attached screenshot on what is appearing for him.
He had tried uploading a test file which is successful, so there is no issue in the connection nor any settings.

Command used : 
```
aspera aoc send --organization xxx-dropzones --workspace "xxx" --dropbox "xxx" --file <filepath> --name "xyz" --message "xyz" -DDD -L ~/.aspera/cli/ --metadata-file ./metadata.txt
```

He finally made the file to 7 parts - 2GB each and uploaded one by one. Customer is not satisfied with this as he want the upload of 14GB file as a single file. He also commented that a 5GB file upload is failing as well and he can upload only small size files without errors.

Can you please check the issue and help resolve the issue

Regards,
Nikita

**Comment by nikkuc01** [comment]
For support on 3.x it is not here. It would be through IBM support site.
>> Though mentioned that we are using old version of cli, still the IBM support said that cli would be supported here. So, I have raised an issue here. I'll check back with them as I have already have a case raised in that site

**Comment by nikkuc01** [comment]
Hi Laurent,

Can you please remove the metadata from your 'create a config' and 'send package' points (where the url, workspace, recipients of our details are mentioned specifically)

Regards,
Nikita

**Comment by laurent-martin** [comment]
done.

**Comment by nikkuc01** [comment]
In --value=@json:recipients as well, please

**Comment by laurent-martin** [comment]
closing, as it is not an `ascli` issue, but previous generation: `aspera` cli.

**Comment by nikkuc01** [comment]
Hi Laurent,

Can you please remove you revision history of the initial post on this issue, by clicking Edit on the comment and delete the previous revisions of the post

Regards,
Nikita

**Comment by nikkuc01** [comment]
Hi @laurent-martin , can you please remove you revision history of the initial post on this issue, by clicking Edit on the comment and delete the previous revisions of the post
