### ISSUE TITLE
Support of encryption at rest (encryption and decryption) : any application

### ISSUE THREAD

**Issue by laurent-martin** [IBM/aspera-cli#66]
An example of use case is the following:
a faspex package has been received, and it is with encryption at rest.

Files have the extension: `.aspera-env`

How to support this in ascli, e.g. 

1. can files be downloaded and decrypted on the fly
2. can files be downloaded encrypted and then decrypted after download ?

**Comment by laurent-martin** [comment]
If no specific parameter is provided, then files are downloaded encrypted.
Then the files can be decrypted using one of those methods:

- graphically: <https://www.ibm.com/docs/en/aspera-connect/4.1?topic=tfc-file-encryption>
- using command line: <https://www.ibm.com/docs/en/ahts/4.3?topic=line-client-side-encryption-rest-ear>

For inline encryption/decryption use the following transfer spec parameters:

```
--ts=@json:'{"EX_ascp_args":["--file-crypt=decrypt"],"EX_at_rest_password":"laurent"}'
```

where `laurent` is ther passphrase.

**Comment by dijjit** [comment]
Much appreciated @laurent-martin . Will try the inline process first.

**Comment by laurent-martin** [comment]
specific trasfer spec parameters EX_ascp_args and EX_at_rest_password can be used.
starting next version (4.6.0), standard parameters content_protection and content_protection_password can also be used.
