### ISSUE TITLE
Issues with Wizard and new AoC UI rollout

### ISSUE THREAD

**Issue by tomwganem** [IBM/aspera-cli#69]
ascli conf wizard --url=https://foo.ibmaspera.com is no longer working

```
ascli conf wizard --url=https://aspera-ops.ibmaspera.com/
ERROR: Other: No known application found at https://aspera-ops.ibmaspera.com/
```

**Comment by dwosk** [comment]
@tomwganem check with latest v4.7.0, I think @laurent-martin fixed this already. 

See here: https://github.com/IBM/aspera-cli/releases/tag/v4.7.0

**Comment by tomwganem** [comment]
Thanks @dwosk !
