### ISSUE TITLE
Review & Address AppScan report

### ISSUE THREAD

**Issue by gegles** [IBM/aspera-cli#74]
Hey @laurent-martin, great if you could take a look into the report [here](https://cloud.appscan.com/main/myapps/a3677bd0-1901-442a-b30b-089f398e2c60/issues). In case you don't have access, here is the PDF version.
[Report_IBM Aspera CLI_2022-04-08.pdf](https://github.com/IBM/aspera-cli/files/8455769/Report_IBM.Aspera.CLI_2022-04-08.pdf)

Thanks!

**Comment by laurent-martin** [comment]
Well, they are all false positives.
OpenSSL::SSL::VERIFY_NONE is the default anyway in webrick for SSLVerifyClient (https://docs.ruby-lang.org/en/2.5.0/WEBrick/Config.html)
only one of them is to ignore server cert if --insecure=yes is used, this is to accept self signed certs, similar to curl "-k"
the one on Kernel.exec is not true, it is SSH.exec which is used to remotely execute ascmd 
the ones for "eval" are also legimitate, anyway: 1: ascli is not a rail application, and if the user can execute ascli, the user can also execute ruby and has shell access and can execute anything anyway.

**Comment by gegles** [comment]
@laurent-martin, I re-run the appscan tool and we now only have 2 (new) issues remaining. See here if you have access. Otherwise I'll send you a new report via slack. Thx!

**Comment by laurent-martin** [comment]
No access, please send in slack
