### ISSUE TITLE
is there any availability to create group in aoc and map into workspace using CLI.

### ISSUE THREAD

**Issue by prabhushankar3** [IBM/aspera-cli#76]
when i tried to create group on AOC using below command it says argument missing. how do we find out the important argument for sub-commands ?

ascli aoc admin resource group create --name=prabhu-test
ERROR: Argument: missing argument (single): creation data (Hash)
Use option -h to get help.

when i  use -h, it showing the default options, how to find out this specific actions arguments ?
ascli aoc admin resource group create -h  

if possible can you check and let me know below are the actions can be done using this aoc CLI method?

creating groups using ascli?
mapping folders from nodes to specific workspace using ascli?
mapping group permissions to the specific folder using ascli?

**Comment by laurent-martin** [comment]
New resources (users, groups, workspaces, etc..) can be created using a command like:

```bash
<%=cmd%> aoc admin res create <resource type> @json:'{<...parameters...>}'
```

Some of the API endpoints are described [here](https://developer.ibm.com/apis/catalog?search=%22aspera%20on%20cloud%20api%22). Sadly, not all.

Nevertheless, it is possible to guess the structure of the creation value by simply dumping an existing resource, and use the same parameters for the creation.

```bash
<%=cmd%> aoc admin res group show 12345 --format=json
```

```json
{"created_at":"2018-07-24T21:46:39.000Z","description":null,"id":"12345","manager":false,"name":"A8Demo WS1","owner":false,"queued_operation_count":0,"running_operation_count":0,"stopped_operation_count":0,"updated_at":"2018-07-24T21:46:39.000Z","saml_group":false,"saml_group_dn":null,"system_group":true,"system_group_type":"workspace_members"}
```

Remove the parameters that are either obviously added by the system: `id`, `created_at`, `updated_at` or optional.

And then craft your command:

```bash
<%=cmd%> aoc admin res group create @json:'{"description":"test to delete","name":"test 1 to delete","saml_group":false}'
```

If the command returns an error, example:

```output
+----+-----------------------------------------------------------------------------------+
| id | status                                                                            |
+----+-----------------------------------------------------------------------------------+
|    | found unpermitted parameters: :manager, :owner, :system_group, :system_group_type |
|    | code: unpermitted_parameters                                                      |
|    | request_id: b0f45d5b-c00a-4711-acef-72b633f8a6ea                                  |
|    | api.ibmaspera.com 422 Unprocessable Entity                                        |
+----+-----------------------------------------------------------------------------------+```

Well, remove the offending parameters and try again.

**Comment by laurent-martin** [comment]
That being said, to create a group, then add it to a worksapce and add users or groups to it:

* Create the group and take note of `id`

```bash
ascli aoc admin res group create @json:'{"name":"group 1","description":"my super group"}'
```

Group: `11111`

* Get the workspace id

```bash
ascli aoc admin res workspace list --query=@json:'{"q":"myworkspace"}' --fields=id --format=csv --display=data
```

Workspace: 22222
 
* Add group to workspace

```bash
ascli aoc admin res workspace_membership create @json:'{"workspace_id":22222,"member_type":"user","member_id":11111}'
```

* Get a user's id

```bash
ascli aoc admin res user list --query=@json:'{"q":"manu.macron@example.com"}' --fields=id --format=csv --display=data
```

User: 33333

* Add user to group

```bash
ascli aoc admin res group_membership create @json:'{"group_id":11111,"member_type":"user","member_id":33333}'
```

**Comment by laurent-martin** [comment]
Note that the `group_membership` resource will be available only post 4.7.0

**Comment by prabhushankar3** [comment]
@laurent-martin  Thanks for guiding me on this, this will really help me to find out more on this CLI based tasks.

also can you post some of example of required argument on creating "shared_create" resource type. 

when i tried using below parameter, it says missing argument. 

ascli aoc admin res workspace --id=83893 shared_create @json:'{"name":"/test-cli-3", "node_id":"19292", "directory":"/test-cli-3", "create_directory":"false" }'

once again thanks for your valuable time. really appreciate you.

**Comment by laurent-martin** [comment]
Hi,

Shared folder creation is not yet supported in ascli, but it will come soon.

**Comment by prabhushankar3** [comment]
Hi,

How do we upload files and folders using this CLI, i tried all the below commands using files resource it says its not available.

ascli aoc files upload --to-folder=/testsrc testfile.bin
ascli aoc files upload -N --to-folder=/ testfile.bin --link=my_aoc_publink_folder
ascli aoc files upload Test.pdf --transfer=node --transfer-info=@json:@stdin:

ascli aoc files upload --to-folder=/testsrc testfile.bin
ERROR: Rest: The resource you were looking for does not exist
code: not_found
request_id: 2fd285c4-8c09-44d6-b1f0-db172a27e8f8
api.ibmaspera.com 404 Not Found
ERROR: Argument: unprocessed values: ["upload", "testfile.bin"]

also i tried using below command its getting error. not sure what is exact syntax for this command.

ascli  aoc admin res node --id=xxxxxxxx--secret=xxxxxxxv4 upload

can you provide any other examples with command for upload and download using this CLI ?

**Comment by laurent-martin** [comment]
The minimalistic command like:

```
ascli aoc files upload 'faux:///10m?10m'
```

will upload a file named `10m` directly in the home of the authenticated user in the default workspace of this user.

To upload a real file, give the path of a real file
To upload to a subfolder , e.g, `abc`, provide option `--to-folder=abc`

Note: when showing command, please use triple ticks to have formated text.

**Comment by prabhushankar3** [comment]
Actually here the requirement is,

I wanted to migrate my on-prem data to aspera on cloud, which option i can use to upload/transfer files from on-prem to AOC,

which you mentioned is client/user based upload examples, but here i wanted to transfer my 1TB data from on-prem to AOC node.

is it possible can we use this CLI to migrate my data ?

**Comment by laurent-martin** [comment]
Yes, sure it is possible, several ways are made available:
1- using "Aspera Connect Client" : <https://www.ibm.com/aspera/connect/>
You can [connect your AoC account](https://www.ibm.com/docs/en/aspera-connect/4.2?topic=wac-adding-aspera-cloud-account-connect-1) and then perform transfers with a simple drag and drop
Note that this option provides the possibility to "sync" a folder.
2- using the AoC web interface and Connect: drag and drop the folder in the browser and transfer will start
3- using this CLI, you can send a whole folder: `ascli aoc files upload /path/to/folder`
This requires proper configuration (easiest is to use the wizard).

**Comment by prabhushankar3** [comment]
@laurent-martin  any update on this ?

**Comment by laurent-martin** [comment]
Well, run with additional option `--log-level=debug`
and check the error message

**Comment by laurent-martin** [comment]
version 4.8 was released
