### ISSUE TITLE
Code 11- An error occured: Internal error - When trying to download package with faspex

### ISSUE THREAD

**Issue by chiparraco** [IBM/aspera-cli#78]
Hello everyone,
I have a problem, I have an aspera faspex server and I can list the packages and do all kinds of operations. Also with the windows gui client I can download without problem, but I can't download the packages with the cli, it's impossible for me.
When I use the command:

```
ascli faspex package recv 76XXXX --url=https://xxxxxxxx.com/aspera/faspex --username=myuser --password=mypass
```

I get the following error message:

E, [2022-06-06T17:47:34.580662 #471] ERROR -- : code: 11
W, [2022-06-06T17:47:34.581197 #471] WARN -- : An error occurred: Internal error
W, [2022-06-06T17:47:34.581272 #471] WARN -- : resuming in 2 seconds (retry left:6)
E, [2022-06-06T17:48:09.400514 #471] ERROR -- : code: 11
W, [2022-06-06T17:48:09.401171 #471] WARN -- : An error occurred: Internal error
E, [2022-06-06T17:48:09.401243 #471] ERROR -- : non-retryable error
ERROR: FASP(ascp): Internal error

I have the sdk installed
ascp ---> /root/.aspera/ascli/sdk/ascp
IBM Aspera SDK ---> /root/.aspera/ascli/sdk

It is a Debian 4.19.194-2.

If I do a config detect to my server url I get:
version | 4.4.1.178477
products | faspex
URL | https://xxxxxxxxxxx/xxxxx/faspex

Any idea what it could be? it's driving me crazy.

**Comment by chiparraco** [comment]
I already used the logs from --log-level=debug
I am going to try the other ways of seeing logs that you have mentioned.
Thank you!

**Comment by chiparraco** [comment]
With the new logs I get a tcp error, if I can list the files from the server, but it does not connect to download them.
Could it be a server thing?
Command: ascli faspex package recv IDPackage --url=https://xxxxxxx-xx-xx.xxxx.com/aspera/faspex --username=xxxxxxx --password=xXxxxx --ts=@json:'{"EX_ascp_args":["-L-"]}

`LOG Configuration: using v2 configuration file "/root/.aspera/ascli/sdk/aspera.conf", user -
LOG Initializing FASP version 4.2.0.183804, license max rate=(unlimited), account no.=1, license no.=57999 product=7
LOG Configured symlink actions: create=1, follow=1, follow_wide=0, skip=0
LOG IBM Aspera SDK version 1.1.1.52
LOG Alternate log directory: "-"
LOG (access key) Not present
ERR [ascp] Failed to connect to faspex@xxxxx-xx-xxx.xxxx.com
ERR [ascp] TCP connect failed, err=110
LOG FASP Session Start uuidxxxxxxxxxxxxxxxxxxxxxx op=recv status=started source=/ES_SG_XXXX0210_01_FXXX.stl - 345353534-3453455534545.aspera-package/PKG - ES_SN_KUNGFA0210_01_FUSED.stl dest=. source_prefix=- local=0.0.0.0:44722 peer=xxx.xxx.xxx:8888 tcp_port=33001 os="Linux 4.19.0-17-amd64 #1 SMP Debian 4.19" ver=4.2.0.183804 lic=7:1:57999 peeros="-" peerver=- peerlic=0:0:0 proto_sess=20003 proto_udp=20000 proto_bwmeas=20000 proto_data=20010
LOG FASP Session Params uuid=a5454545-ffff-4880-adfc-dfdfdfdfdf userid=0 user="faspex" targetrate=500000000 minrate=0 rate_policy=fair cipher=aes-128-cfb resume=0 create=8 ovr=1 times=0 precalc=no precalc_disable=false mf=0 mf_path=- mf_suffix=.aspera-inprogress partial_file_suffix=- files_encrypt=no files_decrypt=no file_csum=NONE dgram_sz=0 tcp_mode=no rtt_auto=yes cookie="xxxxxx" vl_proto_ver=1  peer_vl_proto_ver=0 vl_local=0 vlink_remote=0 vl_sess_id=0 srcbase=- rd_sz=0 wr_sz=0 cluster_num_nodes=1 cluster_node_id=0 cluster_multi_session_threshold=-1 range=0-0 keepalive=no test_login=no proxy_ip=- net_rc_alg=alg_delay exclude_older/newer_than=0/0
LOG Falling back to HTTP
ERR Error setting up HTTPS: missing key file
ERR Error setting up HTTPS: missing certificate file
LOG Error 110 received while reading an HTTP header
LOG http_session=xxxxxxxxxxxxxxxxxxx ended with result:400 completed=0 elapsed_usec=94
E, [2022-06-09T13:46:22.899350 #11671] ERROR -- : code: 11
W, [2022-06-09T13:46:22.900035 #11671]  WARN -- : An error occured: Internal error
W, [2022-06-09T13:46:22.900110 #11671]  WARN -- : resuming in  2 seconds (retry left:6)`

**Comment by chiparraco** [comment]
Solved, it was a firewall problem that was superior to my machine.
Thank you so much for everything.

**Comment by laurent-martin** [comment]
Yes, exact : `TCP connect failed` means the client side (you) coud not reach the remote port.
