### ISSUE TITLE
Packages upload command does not enforce mandatory metadata

### ISSUE THREAD

**Issue by Digi-Deli** [IBM/aspera-cli#79]
Hi there,

when uploading a package without metadata to a workspace using packages command it does not enforce mandatory metadata. The command I run `ascli aoc package send --workspace="<WORKSPACE_NAME>" --value=@json:'{"name":"<NAME_OF_THE_PACKAGE>","recipients":["<SHARED_INBOX_NAME>"]}' <FILE_OR_FOLDER_PATH>` where the shared inbox has mandatory metadata
 
Shared Inbox Metadata configuration
![Screenshot 2022-06-08 at 16 35 58](https://user-images.githubusercontent.com/103125566/172658163-1fb1bfbe-32d7-48da-bdd5-26573ddfd865.png)

Package uploaded
![Screenshot 2022-06-08 at 16 37 07](https://user-images.githubusercontent.com/103125566/172658374-82d2207c-3e5d-497a-a006-0d741b4e3d25.png)

API call to get packages
![Screenshot 2022-06-08 at 16 38 45](https://user-images.githubusercontent.com/103125566/172658727-92b35ff0-a562-4b6c-81fa-033aa5b2e595.png)

Aspera CLI packages show command
![Screenshot 2022-06-08 at 16 39 27](https://user-images.githubusercontent.com/103125566/172658884-012406f1-28a1-4228-a14e-a1993652f54d.png)

The first metadata configuration is pre-populated but the second one (ECCN) is not and it is mandatory.

Is this something you can look into it?

Thank you

**Comment by laurent-martin** [comment]
Well, it could be done on client side, but it shall be a server-side check.

**Comment by laurent-martin** [comment]
some basic validation will be in next version.

also see 
<https://integration-development.ideas.ibm.com/ideas/ASPERAIDEA-I-105>

**Comment by Digi-Deli** [comment]
> Well, it could be done on client side, but it shall be a server-side check, else anyone who use AoC API would have to enforce the rules... and there will always be someone who do not follow the rules.
> 
> Notee that the validation schema can be retrieved with:
> 
> ```
> ascli aoc packages shared_inboxes show 1234 --fields=metadata_schema --format=csv --display=data
> ```

It could but I don't think it should. You can't trust everybody to follow the rules. Besides when trying to send a package via UI that required metadata is enforced.

Thanks for making the changes. By the way I can't see that idea, it says record not found.

**Comment by laurent-martin** [comment]
Here the text of idea:

When a user uses the AoC API to create a package the medata schema shall be also validated on server side.
It seems it is currently only validated on client side.
So, if a user uses the API to create a package, then the user can set any metadata, or simply omit it, even if some are mandatory.

**Comment by laurent-martin** [comment]
Note that the idea was closed with status "Not under consideration"

**Comment by Digi-Deli** [comment]
I guess it's ok as long as the UI and the CLI enforces the metadata to be added. Our customers won't use the API directly only me and my team as we've build some functionality around those APIs.

Thanks though for logging the idea :)

**Comment by laurent-martin** [comment]
It should be soon, I have asked to @gegles
