### ISSUE TITLE
Question: Does the cli support change of folder access level

### ISSUE THREAD

**Issue by Digi-Deli** [IBM/aspera-cli#86]
Hi there,

From the UI after creating a folder you have to share it with people in order for them to see your folders. I was wondering if the cli support changes to the folder access level when using files app. I can create folders using `ascli aoc files mkdir` but I can only access it unless I change the access level of the folder via UI.

Regards

**Comment by laurent-martin** [comment]
Currently the CLI does not allow easily to share folders with others.
Normally this is done by adding "permissions" using the node API and notifying AoC about the change.

There is some stem of code to do that, but it is not finalized:

First list files with their `id`
```
ascli aoc files br / --fields=+id
```

Then show current permissions:

```
ascli aoc files file permission 3383 list
```

There is also a create command, but it does not allow adding others.

in TODO list

**Comment by laurent-martin** [comment]
You can now share folders and un-shared with `ascli` , see [here](https://github.com/IBM/aspera-cli#shared-folders)
