### ISSUE TITLE
Aspera CLI 3.9.6 throwing SSL certificate errors

### ISSUE THREAD

**Issue by Deepak-T-Dasan** [IBM/aspera-cli#88]
SSL certificate was updated on the Faspex server last Saturday, A customer is now reporting that they are getting an error as "Status Code: 0, Error (CURLCode: 60) SSL peer certificate or SSH remote key was not OK". Please guide us as to how we can get around this issue.

**Comment by laurent-martin** [comment]
For ascli https cert error : try —insecure=yes
For ascp cert errors (SSH or HTTPS) there is —ts=@json:’{“sshfp“:null}‘
Check the manual
