### ISSUE TITLE
When I download a package from a workgroup it does not disappear from the server

### ISSUE THREAD

**Issue by rmartinmateos** [IBM/aspera-cli#90]
Hello!
I have a doubt, when I downloaded packages directly from the server, they disappeared from the server once downloaded. Currently the provider uploads them to some Workgroups to differentiate them and I download them through the "recipient='*NameOfWorkGroup' filter 
(ascli faspex package recv $ID --recipient='*xxxxxxxx' --url=https://xxxxxxxxxxxxx/aspera/faspex --username=xxxxxx--password=xxxxxxx --to-folder=. --once-only=yes)
but once downloaded they do not disappear from aspera. This is a nuisance because every time I launch the script that downloads them I duplicate the already downloaded...
Is there a way to remove already downloaded packages, from the server, with the CLI?

Many thanks.

![Untitled2](https://user-images.githubusercontent.com/105369718/188609893-bd07c1ec-82f9-478d-a9e9-88731cfbaba0.png)
![Untitled](https://user-images.githubusercontent.com/105369718/188610818-0fd29c29-5a51-4417-b81a-47ca44b0ecfd.png)

**Comment by laurent-martin** [comment]
There are 2 aspects:
1- the option `--once-only=yes` keeps a trace of downloaded package ids to avoid downloading them again next time
2- on faspex server side, the admin can set a package retention policy to delete packages once they have been downloaded.

**Comment by rmartinmateos** [comment]
Thanks for the answer, the administrator has told me that option 2 is already activated, but even so they are not deleted, I will comment again to see if he has done it correctly.

On the other hand, using the once only yes option, I download a file multiple times, i.e. I use (ascli faspex package recv $ID --recipient='*xxxxxxxx' --url= https://xxxxxxxxxxxxx/ aspera/faspex --username=xxxxxx--password=xxxxxxx --to-folder=. --once-only=yes) and it downloads the file for me, I use it again with the same id and it downloads it again even though I already downloaded it.

**Comment by laurent-martin** [comment]
Yes, right ... the --once-only=yes is active only if you use keyword `ALL` instead of $ID

**Comment by rmartinmateos** [comment]
The problem is that once the packages are downloaded, they are moved to an FTP so that another client organizes them, therefore it will never find them on our disk.

The best thing would be the option of when it is downloaded to be removed from the server, but it seems to not work well...

Thank you very much, I'll keep looking!

**Comment by laurent-martin** [comment]
Note that version 4.9.0 honours option `--once-only=yes` when a single package is downloaded.
It will not be downloaded again if it was downloaded earlier.
