### ISSUE TITLE
ascli conf ascp install is failing in 4.90

### ISSUE THREAD

**Issue by MikeKenno** [IBM/aspera-cli#94]
Hi,

I'm seeing an error when trying to use ascli and there is no FASP installation found

```
ERROR: Other: no FASP installation found
Please check manual on how to install FASP.
Use --log-level=debug to get more details. 
```

On previous versions of ascli running the following  command would rectify it:
`ascli conf ascp install` 

Now when running it I'm seeing:
`ERROR: Rest: eudemo.asperademo.com 404 Not Found`

Cheers

**Comment by laurent-martin** [comment]
ok fixed.

**Comment by MikeKenno** [comment]
Thank you 👍
