### ISSUE TITLE
Error: Failed to open TCP connection for SSH

### ISSUE THREAD

**Issue by f-jx** [IBM/aspera-cli#95]
$ ~/.aspera/connect/bin/ascp -QT -l 300m -P 33001 -L- -i ~/.aspera/connect/etc/aspera_web_key.pem era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR141/009/SRR14159909/SRR14159909_1.fastq.gz fq/raw/

LOG Configuration: using v2 configuration file "/home/js/.aspera/connect/etc/aspera.conf", user -
LOG Initializing FASP version 4.4.1.197 , license max rate=(unlimited), account no.=1, license no.=53 product=53
LOG Configured symlink actions: create=1, follow=1, follow_wide=0, skip=0
LOG Aspera Connect version 4.2.3.197

LOG Alternate log directory: "-"
LOG (access key) Not present
ERR [ascp] Failed to connect to era-fasp@fasp.sra.ebi.ac.uk
ERR [ascp] TCP connect failed, err=110
ERR Failed to open TCP connection for SSH
ascp: Failed to open TCP connection for SSH, exiting.
LOG FASP Session Start uuid=c4b4a68a-c158-4cde-a11e-323a36a7b8bc op=recv status=failed errcode=14 errstr="Unable to receive a valid stop message (pmtu-brtt)" source=vol1/fastq/SRR141/009/SRR14159909/SRR14159909_1.fastq.gz dest=fq/raw source_prefix=- local=0.0.0.0:52309 peer=193.62.193.135:8888 tcp_port=33001 os="Linux 4.18.0-348.7.1.el8_5.x86_64 #1 SMP" ver=4.4.1.197  lic=53:1:53 peeros="-" peerver=- peerlic=0:0:0 proto_sess=20003 proto_udp=20000 proto_bwmeas=20000 proto_data=20011
LOG FASP Session Params uuid=c4b4a68a-c158-4cde-a11e-323a36a7b8bc userid=0 user="era-fasp" targetrate=300000000 minrate=0 rate_policy=fair cipher=none resume=0 create=0 extra_create=0 ovr=1 times=0 precalc=no precalc_disable=false mf=0 mf_path=- mf_suffix=.aspera-inprogress partial_file_suffix=- files_encrypt=no files_decrypt=no file_csum=NONE dgram_sz=0 tcp_mode=no rtt_auto=yes cookie="-" vl_proto_ver=1  peer_vl_proto_ver=0 vl_local=0 vlink_remote=0 vl_sess_id=0 srcbase=- rd_sz=0 wr_sz=0 cluster_num_nodes=1 cluster_node_id=0 cluster_multi_session_threshold=-1 range=0-0 keepalive=no test_login=no proxy_ip=- net_rc_alg=alg_delay exclude_older/newer_than=0/0

Session Stop  (Error: Failed to open TCP connection for SSH)
LOG FASP Session Stop uuid=c4b4a68a-c158-4cde-a11e-323a36a7b8bc op=recv status=failed errcode=14 errstr="Unable to receive a valid stop message (pmtu-brtt)" source=vol1/fastq/SRR141/009/SRR14159909/SRR14159909_1.fastq.gz dest=fq/raw source_prefix=- local=0.0.0.0:52309 peer=193.62.193.135:8888 tcp_port=33001 os="Linux 4.18.0-348.7.1.el8_5.x86_64 #1 SMP" ver=4.4.1.197  lic=53:1:53 peeros="-" peerver=- peerlic=0:0:0 proto_sess=20003 proto_udp=20000 proto_bwmeas=20000 proto_data=20011
LOG FASP Session Params uuid=c4b4a68a-c158-4cde-a11e-323a36a7b8bc userid=0 user="era-fasp" targetrate=300000000 minrate=0 rate_policy=fair cipher=none resume=0 create=0 extra_create=0 ovr=1 times=0 precalc=no precalc_disable=false mf=0 mf_path=- mf_suffix=.aspera-inprogress partial_file_suffix=- files_encrypt=no files_decrypt=no file_csum=NONE dgram_sz=0 tcp_mode=no rtt_auto=yes cookie="-" vl_proto_ver=1  peer_vl_proto_ver=0 vl_local=0 vlink_remote=0 vl_sess_id=0 srcbase=- rd_sz=0 wr_sz=0 cluster_num_nodes=1 cluster_node_id=0 cluster_multi_session_threshold=-1 range=0-0 keepalive=no test_login=no proxy_ip=- net_rc_alg=alg_delay exclude_older/newer_than=0/0
LOG FASP Session Statistics [Receiver] id=c4b4a68a-c158-4cde-a11e-323a36a7b8bc delay=0ms rex_delay=0ms ooo_delay=0ms solicited_rex=0.00% rcvd_rex=0.00% rcvd_dups=0.00% ave_xmit_rate 0.00Kbps effective=0.00% effective_rate=0.00Kbps (detail: good_blks 0 bl_total 0 bl_orig 0 bl_rex 0 dup_blks 0 dup_last_blks 0 drop_blks_xnf 0) (sndr ctl: sent 0 rcvd 0 lost 0 lost 0.00%) (rcvr ctl: sent 0 rcvd 0 lost 0 lost 0.00%) (rex  ctl: sent 0 rcvd 0 lost 0 lost 0.00%) (progress: tx_bytes 0 file_bytes 0 tx_time 0) rex_xmit_blks 0  xmit_total 0 rex_xmit_pct 0.00%

**Comment by laurent-martin** [comment]
Hi,

First of all, this project (`ascli`) is not exactly the right place to ask: The right place is either to the server providers: [ENA](https://www.ebi.ac.uk/) or the [IBM support](https://www.ibm.com/mysupport).

You probably based your command on the following manual as ENA:
<https://ena-docs.readthedocs.io/en/latest/retrieval/file-download.html#using-aspera>

This manual is a bit ageing.

Your first problem is that your client system cannot reach the TCP port 33001 on server: `fasp.sra.ebi.ac.uk`

You can refer to this:

<https://www.ibm.com/docs/en/asdc/4.4?topic=upgrades-configuring-firewall>

If you have the `telnet`command available, or equivalent (`putty.exe`, `nc` , ...), you can test the TCP connectivity like this:

```
telnet fasp.sra.ebi.ac.uk 33001
```

The result shall be:

```
Trying 193.62.193.135...
Connected to fasp.ebi.ac.uk.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.4
```

But if you get:

```
Trying 193.62.193.135...
telnet: connect to address 193.62.193.135: Connection refused
telnet: Unable to connect to remote host
```

It means that you have a firewall in the middle that is not allowing you for a direct connection, then contact your local network administrator, or try again from another network (e.g. home)

Once you have resolved the problem of port, you will have another problem:

The DSA key used here is no more provided as part of the official Aspera client applications.

A solution is to use `ascli`.

The equivalent command line would be:

```
ascli server --url=ssh://fasp.sra.ebi.ac.uk:33001 --username=era-fasp \
--ssh-keys=@ruby:Fasp::Installation.instance.bypass_keys.first \
--ts=@json:'{"target_rate_kbps":300000}' \
--to-folder=fq/raw/ \
vol1/fastq/SRR141/009/SRR14159909/SRR14159909_1.fastq.gz 
```

**Comment by f-jx** [comment]
Thanks for your exhaustive reply!
