### ISSUE TITLE
Aspera Client cannot use function rename

### ISSUE THREAD

**Issue by teeraw-22** [IBM/aspera-cli#96]
Aspera Client cannot use function rename.

I run command:
ascli share repo rename Test_repo path_src=test.txt path_dst=test2.txt --url=https://{MY-ASPERA-SHARE} --username={MY-USERID} --password={MY-PASSWORD}  --insecure=yes --log_level=debug

Then error as below:
ERROR -- : No such file or directory 

But I checked path/file on Aspera shares is corrected.

**Comment by laurent-martin** [comment]
do not give the parameter name, just the value:

```bash
ascli share repo rename Test_repo test.txt test2.txt --url=https://{MY-ASPERA-SHARE} --username={MY-USERID} --password={MY-PASSWORD} --insecure=yes --log_level=debug
```

**Comment by teeraw-22** [comment]
Thank you, problem solved!
