### ISSUE TITLE
Aspera cli upload failure

### ISSUE THREAD

**Issue by Suren-Lilly** [IBM/aspera-cli#98]
i get the below error when i try to browse share from linux cli.

D, [2022-12-13T15:16:05.115536 #1542537] DEBUG -- net.ssh.transport.server_version[bb8]: local is `SSH-2.0-Ruby/Net::SSH_6.1.0 x86_64-linux'

ERROR: Other: connection closed by remote host

/home/svc_aspera/.local/share/gem/ruby/gems/net-ssh-6.1.0/lib/net/ssh/transport/server_version.rb:57:in `rescue in block (2 levels) in negotiate!': connection closed by remote host (Net::SSH::Disconnect)

**Comment by laurent-martin** [comment]
Best is if you share the command line used. (redacting hostnames, usernames and password).

access to shares should be like this:

```
ascli shares --url=https://shares.example.com --username=xxx --password=yyy browse /
```

**Comment by Suren-Lilly** [comment]
We used the below commands to save.

ascli config preset update myserver --url=ssh://host:port --username=asperaweb --password=_pass_here_
updated: myserver
ascli config preset set default server myserver
updated: default&rarr;server to myserver
ascli server browse /folder




From: Laurent Martin ***@***.***>
Sent: Thursday, December 15, 2022 8:37 PM
To: IBM/aspera-cli ***@***.***>
Cc: Surendranathan Ravimanoharan - Network ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [IBM/aspera-cli] Aspera cli upload failure (Issue #98)

EXTERNAL EMAIL: Use caution before replying, clicking links, and opening attachments.



Best is if you share the command line used. (redacting hostnames, usernames and password).

access to shares should be like this:

ascli shares --url=https://shares.example.com --username=xxx --password=yyy browse /

-

**Comment by laurent-martin** [comment]
This command is to access an Aspera HSTS directly through the SSH interface.

But for Aspera Shares, the correct commands are:

```
ascli config preset update mysharesconf --url=https://shares.example.com --username=_user_here_ --password=_pass_here_
ascli config preset set default shares mysharesconf
ascli shares browse /folder
```

Again, the `server` plugin is for direct HSTS access.

For **Shares**, ... use the `shares` command.

(In your case, you are using a Shares app, and HSTS is on a different server (through aspera proxy).)

**Comment by Suren-Lilly** [comment]
Please see the error:
ERROR: Argument: unknown value for command: browse
Use:
- admin
- health
- repository
Use option -h to get help.
ERROR: Argument: unprocessed values: ["/r_Labcorp_to_Lilly"]
/home/svc_aspera/.local/share/gem/ruby/gems/aspera-cli-4.10.0/lib/aspera/cli/manager.rb:75:in `get_from_list': unknown value for command: browse (Aspera::Cli::CliBadArgument)

'browse' isn't a valid argument for 'ascli shares'




From: Laurent Martin ***@***.***>
Sent: Thursday, December 15, 2022 8:46 PM
To: IBM/aspera-cli ***@***.***>
Cc: Surendranathan Ravimanoharan - Network ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [IBM/aspera-cli] Aspera cli upload failure (Issue #98)

EXTERNAL EMAIL: Use caution before replying, clicking links, and opening attachments.



This command is to access an Aspera HSTS directly through the SSH interface.

But for Aspera Shares, the correct commands are:

ascli config preset update mysharesconf --url=https://shares.example.com --username=_user_here_ --password=_pass_here_

ascli config preset set default shares mysharesconf

ascli shares browse /folder

Again, the server plugin is for direct HSTS access.

For Shares, ... use the shares command.

(In your case, you are using a Shares app, and HSTS is on a different server (through aspera proxy).)

-

**Comment by laurent-martin** [comment]
I apologize, there was a typo (fixed above), the correct command is:

```
ascli shares repo browse /r_Labcorp_to_Lilly
```

**Comment by Suren-Lilly** [comment]
Hi Martin,

It worked.

Can you please share the command to upload file or folder to shares.

From: Laurent Martin ***@***.***>
Sent: Thursday, December 15, 2022 9:01 PM
To: IBM/aspera-cli ***@***.***>
Cc: Surendranathan Ravimanoharan - Network ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [IBM/aspera-cli] Aspera cli upload failure (Issue #98)

EXTERNAL EMAIL: Use caution before replying, clicking links, and opening attachments.



I apologize, there was a typo (fixed above), the correct command is:

ascli shares repo browse /r_Labcorp_to_Lilly

-

**Comment by Suren-Lilly** [comment]
Browse worked,

issue with upload:

[~]$ ascli server upload josh_test2.txt --to-folder=/r_Labcorp_to_Lilly
ERROR: Other: ERROR: transfer spec with token required
ERROR: Argument: unprocessed values: ["upload", "josh_test2.txt"]
Use --log-level=debug to get more details.


please see if you can assist.

**Comment by laurent-martin** [comment]
eh eh, :)...

again, command is `shares`, always, for shares.
and repository commands are under: `ascli shares repo`

I suggest you delete your old configuration like this, to avoid confusion:

```
ascli config preset delete myserver
ascli conf preset unset default server
```

you can list shares repository commands like this:

```
ascli shares repo
```

Some commands are listed here:

https://github.com/IBM/aspera-cli#plugin-ibm-aspera-shares

So, the correct command is:

```
ascli shares repo upload josh_test2.txt --to-folder=/r_Labcorp_to_Lilly
```

you can adjust transfer parameters like this:

```
ascli shares repo upload josh_test2.txt --to-folder=/r_Labcorp_to_Lilly --ts=@json:'{"target_rate_kbps":100000,"resume_policy":"sparse_csum"}'

transfer parameters are explained here:

https://github.com/IBM/aspera-cli#transfer-parameters


```

**Comment by Suren-Lilly** [comment]
Martin, thanks much. it worked now.
